SET @DT_INI := 20200101;
SET @DT_FIM := 20200131;
SET @AA_MM_INI := EXTRACT(YEAR_MONTH FROM @DT_INI);
SET @AA_MM_FIM := EXTRACT(YEAR_MONTH FROM @DT_FIM);
SET @ANO_REF:= YEAR(@DT_FIM);
SET @MES_REF:= MONTH(@DT_FIM);

-- INDICADOR 2 - EQP TEC
DROP TEMPORARY TABLE IF EXISTS fluxoTrabalho.TMP_EVT;
CREATE TEMPORARY TABLE fluxoTrabalho.TMP_EVT ( PRIMARY KEY (AA_EVT, NR_EVT) ) ENGINE=MEMORY AS (
	SELECT 
		S.CD_PROJ, S.CD_SUB_PROJ, E.AA_EVT, E.NR_EVT, E.TS_CRIC_EVT
	FROM fluxoTrabalho.evt E
	INNER JOIN fluxoTrabalho.sub_proj S ON (S.CD_PROJ = E.CD_PROJ AND S.CD_SUB_PROJ = E.CD_SUB_PROJ)
	INNER JOIN fluxoTrabalho.proj P ON (P.CD_PROJ = S.CD_PROJ AND P.CD_PGM = 9)
	WHERE E.CD_PRF_EXEC <> 8558 
    AND E.CD_FASE_EVT NOT IN(4, 5)
    -- AND EXTRACT(YEAR_MONTH FROM E.TS_CRIC_EVT) = @AA_MM_IND2
    AND EXTRACT(YEAR_MONTH FROM E.TS_CRIC_EVT) BETWEEN @AA_MM_INI AND @AA_MM_FIM
    
	ORDER BY E.AA_EVT, E.NR_EVT 
);
--  SELECT * FROM fluxoTrabalho.TMP_EVT ORDER BY 3;

DROP TEMPORARY TABLE IF EXISTS fluxoTrabalho.TMP_EVT_EQT;
CREATE TEMPORARY TABLE fluxoTrabalho.TMP_EVT_EQT ( PRIMARY KEY (AA_EVT, NR_EVT, NR_SEQ_EQP_TCN) ) ENGINE=MEMORY AS (
	SELECT 
		E.CD_PROJ, E.CD_SUB_PROJ, E.AA_EVT, E.NR_EVT, E.TS_CRIC_EVT, IFNULL(ET.NR_SEQ_EQP_TCN, 1) AS NR_SEQ_EQP_TCN, IFNULL(ET.TS_INC_EQP_TCN, CURDATE()) AS TS_INC_EQP_TCN, ET.IN_VGT_EQP_TCN, IFNULL(ET.CD_ESPD_EQP_TCN ,2) AS CD_ESPD_EQP_TCN
	FROM fluxoTrabalho.TMP_EVT E
	LEFT JOIN fluxoTrabalho.eqp_tcn ET ON (ET.AA_EVT = E.AA_EVT AND ET.NR_EVT = E.NR_EVT)
	WHERE ET.CD_ESPD_EQP_TCN IN(2, 4, 6, 22, 24, 107, 109)
    OR(ET.CD_ESPD_EQP_TCN IS NULL)
);
-- SELECT * FROM fluxoTrabalho.TMP_EVT_EQT;

DROP TEMPORARY TABLE IF EXISTS fluxoTrabalho.TMP_EVT_PRIM_EQP;
CREATE TEMPORARY TABLE fluxoTrabalho.TMP_EVT_PRIM_EQP ( PRIMARY KEY (AA_EVT, NR_EVT, NR_SEQ_EQP_TCN) ) ENGINE=MEMORY AS (
	SELECT 
		E.CD_PROJ, E.CD_SUB_PROJ, E.AA_EVT, E.NR_EVT, E.TS_CRIC_EVT,  E.TS_INC_EQP_TCN, E.NR_SEQ_EQP_TCN, E.IN_VGT_EQP_TCN, E.CD_ESPD_EQP_TCN  
    FROM fluxoTrabalho.TMP_EVT_EQT E
    LEFT JOIN (SELECT A.AA_EVT, A.NR_EVT, MIN(IFNULL(B.NR_SEQ_EQP_TCN, 1)) AS MIN_SEQ FROM fluxoTrabalho.evt A LEFT JOIN  fluxoTrabalho.eqp_tcn B ON(B.AA_EVT = A.AA_EVT AND B.NR_EVT = A.NR_EVT) 
				WHERE B.CD_ESPD_EQP_TCN IN(2, 4, 6, 22, 24, 107, 109) OR B.CD_ESPD_EQP_TCN IS NULL  GROUP BY AA_EVT, NR_EVT) F 
    ON(F.AA_EVT = E.AA_EVT AND F.NR_EVT = E.NR_EVT)
    
    WHERE E.NR_SEQ_EQP_TCN =  F.MIN_SEQ
  --  GROUP BY E.AA_EVT, E.NR_EVT
);
 -- SELECT * FROM fluxoTrabalho.TMP_EVT_PRIM_EQP GROUP BY CD_PROJ, CD_SUB_PROJ, AA_EVT, NR_EVT;

SET @ORC_2 := (SELECT COUNT(DISTINCT CONCAT(E.AA_EVT,'',E.NR_EVT)) FROM fluxoTrabalho.TMP_EVT E);
SET @RLZ_2 := (
	SELECT 
		COUNT(CASE WHEN DIASDIF = 1 THEN TRUE END) AS RLZ_2 
	FROM (
		SELECT 
			E.AA_EVT, E.NR_EVT, IF(COALESCE(DATEDIFF(E.TS_INC_EQP_TCN,E.TS_CRIC_EVT),999)>7,FALSE,TRUE) DIASDIF, EXTRACT(YEAR_MONTH FROM E.TS_CRIC_EVT) AS AA_MM  
		FROM fluxoTrabalho.TMP_EVT_EQT E
		INNER JOIN fluxoTrabalho.TMP_EVT_PRIM_EQP M ON (E.AA_EVT = M.AA_EVT AND E.NR_EVT = M.NR_EVT AND E.NR_SEQ_EQP_TCN = M.NR_SEQ_EQP_TCN)
	) A
);
 
DROP TEMPORARY TABLE IF EXISTS fluxoTrabalho.TMP_APURACAO;

CREATE TEMPORARY TABLE fluxoTrabalho.TMP_APURACAO
SELECT 
	E.CD_PROJ, E.CD_SUB_PROJ, E.AA_EVT, E.NR_EVT, E.NR_SEQ_EQP_TCN, E.TS_CRIC_EVT,  E.TS_INC_EQP_TCN,  E.IN_VGT_EQP_TCN, E.CD_ESPD_EQP_TCN,
    DATEDIFF(IFNULL(E.TS_INC_EQP_TCN, CURDATE()),E.TS_CRIC_EVT) AS QT_DIAS,
    IF(COALESCE(DATEDIFF(IFNULL(E.TS_INC_EQP_TCN, CURDATE()),E.TS_CRIC_EVT),999)>7,FALSE,TRUE) DIASDIF, 
    EXTRACT(YEAR_MONTH FROM E.TS_CRIC_EVT) AS AA_MM  
FROM fluxoTrabalho.TMP_EVT_EQT E
INNER JOIN fluxoTrabalho.TMP_EVT_PRIM_EQP M ON (E.AA_EVT = M.AA_EVT AND E.NR_EVT = M.NR_EVT AND E.NR_SEQ_EQP_TCN = M.NR_SEQ_EQP_TCN)

;

/*SELECT * 
FROM fluxoTrabalho.TMP_APURACAO WHERE DIASDIF = 1;*/
 
SET @QT_TOTAL := (SELECT COUNT(*) FROM fluxoTrabalho.TMP_APURACAO);
SET @QT_REALZ  := (SELECT COUNT(*) FROM fluxoTrabalho.TMP_APURACAO WHERE DIASDIF = 1);
SET @PC_REALZ := (@QT_REALZ/ @QT_TOTAL );


/** ***********************GAC01************************** */
DROP TABLE IF EXISTS gac.CAD_EQP_TEC_GAC1;
CREATE TABLE gac.CAD_EQP_TEC_GAC1

SELECT DISTINCT
1 AS cd_bloc, 
169 as cd_in, 
10000 as cd_prf_depe, 
@ANO_REF as ano_ref,  
@MES_REF as mes_ref, 
DATEDIFF(CURDATE() , 19600101) as dt_prct,
ROUND(@PC_REALZ, 4) as pc_rstd,
CASE 
	WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.0000 AND 0.7999 THEN 1.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.8000 AND 0.8579 THEN 2.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.8580 AND 0.9039 THEN 3.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9040 AND 0.9419 THEN 4.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9420 AND 0.9689 THEN 5.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9690 AND 0.9799 THEN 6.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9800 AND 0.9879 THEN 7.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9880 AND 0.9939 THEN 8.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9940 AND 0.9979 THEN 9.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9980 AND 1.000 THEN 10.0000
END AS cd_rstd,
concat('PERÍODO DE APURAÇÃO: ', @DT_INI, ' A ', @DT_FIM) as tx_jst_rstd

UNION

SELECT DISTINCT
1 AS cd_bloc, 
169 as cd_in, 
8558 as cd_prf_depe, 
@ANO_REF as ano_ref,  
@MES_REF as mes_ref, 
DATEDIFF(CURDATE() , 19600101) as dt_prct,
ROUND(@PC_REALZ, 4) as pc_rstd,
CASE 
	WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.0000 AND 0.7999 THEN 1.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.8000 AND 0.8579 THEN 2.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.8580 AND 0.9039 THEN 3.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9040 AND 0.9419 THEN 4.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9420 AND 0.9689 THEN 5.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9690 AND 0.9799 THEN 6.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9800 AND 0.9879 THEN 7.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9880 AND 0.9939 THEN 8.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9940 AND 0.9979 THEN 9.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9980 AND 1.000 THEN 10.0000
END AS cd_rstd,
concat('PERÍODO DE APURAÇÃO: ', @DT_INI, ' A ', @DT_FIM) as tx_jst_rstd

UNION

SELECT DISTINCT
1 AS cd_bloc, 
169 as cd_in, 
7421 as cd_prf_depe, 
@ANO_REF as ano_ref,  
@MES_REF as mes_ref, 
DATEDIFF(CURDATE() , 19600101) as dt_prct,
ROUND(@PC_REALZ, 4) as pc_rstd,
CASE 
	WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.0000 AND 0.7999 THEN 1.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.8000 AND 0.8579 THEN 2.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.8580 AND 0.9039 THEN 3.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9040 AND 0.9419 THEN 4.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9420 AND 0.9689 THEN 5.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9690 AND 0.9799 THEN 6.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9800 AND 0.9879 THEN 7.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9880 AND 0.9939 THEN 8.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9940 AND 0.9979 THEN 9.0000
    WHEN ROUND((@PC_REALZ), 4) BETWEEN  0.9980 AND 1.000 THEN 10.0000
END AS cd_rstd,
concat('PERÍODO DE APURAÇÃO: ', @DT_INI, ' A ', @DT_FIM) as tx_jst_rstd;


/** ***********************GAC02************************** */
DROP TABLE IF EXISTS gac.CAD_EQP_TEC_GAC2;
CREATE TABLE gac.CAD_EQP_TEC_GAC2

SELECT DISTINCT
116 as cd_vrv,  -- QT INDICAÃ‡Ã•ES DE EQUIPE EM ATÉ 7 DIAS DO CADASTRAMENTO DO PROCESSO
10000 as cd_prf_depe, 
@ANO_REF as ano_ref,  
@MES_REF as mes_ref,  
@QT_REALZ as vl_vrv, 
169 as cd_in

UNION 

SELECT DISTINCT
117 as cd_crv,  -- QT TOTAL DE PROCESSOS CADASTRADOS
10000 as cd_prf_depe, 
@ANO_REF as ano_ref,  
@MES_REF as mes_ref,  
@QT_TOTAL as vl_vrv, 
169 as cd_in

UNION 

SELECT DISTINCT
116 as cd_vrv,  -- QT INDICAÃ‡Ã•ES DE EQUIPE EM ATÉ 7 DIAS DO CADASTRAMENTO DO PROCESSO
8558 as cd_prf_depe, 
@ANO_REF as ano_ref,  
@MES_REF as mes_ref,  
@QT_REALZ as vl_vrv, 
169 as cd_in

UNION 


SELECT DISTINCT
117 as cd_crv,  -- QT TOTAL DE PROCESSOS CADASTRADOS
8558 as cd_prf_depe, 
@ANO_REF as ano_ref,  
@MES_REF as mes_ref,  
@QT_TOTAL as vl_vrv, 
169 as cd_in

UNION 

SELECT DISTINCT
116 as cd_vrv,  -- QT INDICAÃ‡Ã•ES DE EQUIPE EM ATÉ 7 DIAS DO CADASTRAMENTO DO PROCESSO
7421 as cd_prf_depe, 
@ANO_REF as ano_ref,  
@MES_REF as mes_ref,  
@QT_REALZ as vl_vrv, 
169 as cd_in

UNION 

SELECT DISTINCT
117 as cd_crv,  -- QT TOTAL DE PROCESSOS CADASTRADOS
7421 as cd_prf_depe, 
@ANO_REF as ano_ref,  
@MES_REF as mes_ref,  
@QT_TOTAL as vl_vrv, 
169 as cd_in;



/** ***********************GAC03************************** */
DROP TABLE IF EXISTS gac.CAD_EQP_TEC_GAC3;
CREATE TABLE gac.CAD_EQP_TEC_GAC3
SELECT DISTINCT
23 as cd_evt, 
169 as cd_in, 
2 as qlc_evt, 
7421 as cd_prf_depe,
QUOTE(CONCAT(A.AA_EVT,' ',  A.NR_EVT)) as nr_doc, 
@ANO_REF as ano_ref,  
@MES_REF as mes_ref, 
DATEDIFF(CURDATE() , 19600101) as dt_prct

FROM  fluxoTrabalho.TMP_EVT A
LEFT JOIN fluxoTrabalho.TMP_APURACAO E ON(E.AA_EVT = A.AA_EVT AND E.NR_EVT = A.NR_EVT)
WHERE DIASDIF <> 1

ORDER BY A.AA_EVT, A.NR_EVT;




DROP TABLE gac.CAD_EQP_TEC;
CREATE TABLE gac.CAD_EQP_TEC


SELECT A.CD_PROJ, F.NM_PROJ, A.CD_SUB_PROJ, G.NM_SUB_PROJ, A.AA_EVT, A.NR_EVT , E.NR_SEQ_EQP_TCN, A.TS_CRIC_EVT,  E.TS_INC_EQP_TCN,  E.IN_VGT_EQP_TCN, E.CD_ESPD_EQP_TCN, 

E.QT_DIAS, E.DIASDIF, EXTRACT(YEAR_MONTH FROM A.TS_CRIC_EVT) AS AA_MM  

FROM  fluxoTrabalho.TMP_EVT A
LEFT JOIN (SELECT 
				E.CD_PROJ, E.CD_SUB_PROJ, E.AA_EVT, E.NR_EVT, E.NR_SEQ_EQP_TCN, E.TS_CRIC_EVT,  E.TS_INC_EQP_TCN,  E.IN_VGT_EQP_TCN, E.CD_ESPD_EQP_TCN,
				DATEDIFF(IFNULL(E.TS_INC_EQP_TCN, CURDATE()),E.TS_CRIC_EVT) AS QT_DIAS,
				IF(COALESCE(DATEDIFF(IFNULL(E.TS_INC_EQP_TCN, CURDATE()),E.TS_CRIC_EVT),999)>7,FALSE,TRUE) DIASDIF, 
				EXTRACT(YEAR_MONTH FROM E.TS_CRIC_EVT) AS AA_MM  
			FROM fluxoTrabalho.TMP_EVT_EQT E
			INNER JOIN fluxoTrabalho.TMP_EVT_PRIM_EQP M ON (E.AA_EVT = M.AA_EVT AND E.NR_EVT = M.NR_EVT AND E.NR_SEQ_EQP_TCN = M.NR_SEQ_EQP_TCN)) E 
ON(E.AA_EVT = A.AA_EVT AND E.NR_EVT = A.NR_EVT)
LEFT JOIN fluxoTrabalho.proj F ON(F.CD_PROJ = A.CD_PROJ)
LEFT JOIN fluxoTrabalho.sub_proj G ON(G.CD_SUB_PROJ = A.CD_SUB_PROJ)

;

-- SELECIONA AS TABELAS COM A FORMATAÇÃO NECESSÁRIA PARA RODAR NO SAS

SELECT 
	'VALUES(',
	cd_bloc, 
	',',
	cd_in,
	',',
	cd_prf_depe,
	',',
	ano_ref,
	',',
	mes_ref,
	',',
	dt_prct,
	',',
	pc_rstd,
	',', 
	cd_rstd,
	',',
	QUOTE(tx_jst_rstd),
	')'
FROM gac.CAD_EQP_TEC_GAC1
;

SELECT
	'VALUES(',
	cd_vrv,
	',',
	cd_prf_depe,
	',',
	ano_ref,
	',',
	mes_ref,
	',',
	vl_vrv,
	',',
	cd_in,
	')'
FROM 
	gac.CAD_EQP_TEC_GAC2
;



SELECT 
	'VALUES(',
	cd_evt,
	',',
	cd_in,
	',',
	qlc_evt,
	',',
	cd_prf_depe,
	',',
	nr_doc,
	',',
	ano_ref,
	',',
	mes_ref,
	',',
	dt_prct,
	')'
FROM 
	gac.CAD_EQP_TEC_GAC3
;
