SET @INI_CMP := 20200101;
SET @FIM_CMP := 20200131;
SET @AA_MM_INI := EXTRACT(YEAR_MONTH FROM @INI_CMP);
SET @AA_MM_FIM := EXTRACT(YEAR_MONTH FROM @FIM_CMP);
SET @ANO_REF:= YEAR(@INI_CMP);
SET @MES_REF:= MONTH(@FIM_CMP);

### TABELA AUXILIAR DE EXTRAÇÃO PDCON
/*CREATE TABLE fluxoAux.PDCON_FILTRADO*/
DELETE FROM fluxoAux.PDCON_FILTRADO /*WHERE DT_CRIC_EVT BETWEEN @INI_CMP AND @FIM_CMP*/;
INSERT INTO fluxoAux.PDCON_FILTRADO
SELECT DISTINCT 
	A.CD_SUB_PROJ,
	A.AA_EVT, 
	A.NR_EVT, 
	A.TX_EVT,
	A.CD_FASE_EVT, 
	A.CD_PRF_EXEC, 
	I.VL_ATB_EVT_INT AS PRF_DEMAND, 
    O.NM_UOR_RED AS DEMAND,
	IFNULL(L.CD_PRF, 0) AS PRF_CESUP_REDE, 
	L.NM_UOR_RED AS CESUP_REDE,
	IFNULL(G.CD_PRF, 0) AS PRF_DIR,
	G.NM_UOR_RED AS DIRETORIA,
    R.CD_PRF AS PRF_VP, 
    R.NM_UOR_RED AS VP,
	DATE(A.TS_CRIC_EVT) AS DT_CRIC_EVT,
	A.CD_USU_CRIC_EVT, 
	H.prefixo_lotacao AS PRF_USU_CRIC,
	A.DT_INC_EVT, 
	A.DT_FIM_EVT, 
    P.VL_ATB_EVT_INT AS CD_RES_PROC,
    Q.TX_LS_OPC_ATB AS RES_PROC,
    M.VL_ATB_EVT_INT,
	N.TX_LS_OPC_ATB AS EQD_LGAL,
	T.TX_LS_OPC_ATB AS SINISTRO,
	B.VL_ATB_EVT_DT AS DT_LIM , 
	C.VL_ATB_EVT_INT AS PZ_ETGA, 
	D.VL_ATB_EVT_INT AS PZ_AVL, 
	CASE 
        -- ALTERAÇÃO SOLICITADA POR DICAD DEMANDA 2019/144833 - INÍCIO
        -- WHEN A.CD_SUB_PROJ IN(117, 216, 217) THEN 26
        WHEN A.CD_SUB_PROJ IN(216) THEN 26  										
        WHEN A.CD_SUB_PROJ IN(117, 217) THEN 15
        -- ALTERAÇÃO SOLICITADA POR DICAD DEMANDA 2019/144833 - FIM
		WHEN A.CD_SUB_PROJ IN(68, 69, 73, 74, 208, 215, 218, 219, 220, 222) THEN 30
		WHEN A.CD_SUB_PROJ IN (212, 214, 225) THEN 33
		WHEN A.CD_SUB_PROJ IN (213) THEN 43
		WHEN A.CD_SUB_PROJ IN(210, 211, 238, 363) THEN 132
	END AS PZ_IND,      -- PRAZO DE LICITAÇÃO POR SUBPROJETO EM DIAS
	CASE 
		WHEN A.CD_SUB_PROJ IN(68, 69, 73, 74, 92, 115, 117, 169, 208, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223) THEN 1
		WHEN A.CD_SUB_PROJ IN (210, 211, 238, 363) THEN 1.5
		WHEN A.CD_SUB_PROJ IN (212, 225) THEN 2
	END AS PESO_IND     -- PESO DO INDICADOR POR SUBPROJETO EM DIAS

	FROM fluxoTrabalho.evt A

	LEFT JOIN fluxoTrabalho.ctu_atb_evt B ON(B.CD_SUB_PROJ = A.CD_SUB_PROJ AND B.AA_EVT = A.AA_EVT AND B.NR_EVT = A.NR_EVT AND B.CD_ATB IN(407, 441, 444, 447, 456, 457, 460, 463, 466, 469, 472, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530))  -- DATA LIMITE
	LEFT JOIN fluxoTrabalho.ctu_atb_evt C ON(C.CD_SUB_PROJ = A.CD_SUB_PROJ AND C.AA_EVT = A.AA_EVT AND C.NR_EVT = A.NR_EVT AND C.CD_ATB IN(406, 442, 445, 448, 452, 454, 458, 461, 464, 467, 470, 473))  -- PRAZO DE ENTREGA
	LEFT JOIN fluxoTrabalho.ctu_atb_evt D ON(D.CD_SUB_PROJ = A.CD_SUB_PROJ AND D.AA_EVT = A.AA_EVT AND D.NR_EVT = A.NR_EVT AND D.CD_ATB IN(410, 443, 446, 449, 453, 455, 459, 462, 465, 468, 471, 474))    -- PRAZO AVALIACAO
	LEFT JOIN fluxoTrabalho.ctu_atb_evt I ON(I.CD_SUB_PROJ = A.CD_SUB_PROJ AND I.AA_EVT = A.AA_EVT AND I.NR_EVT = A.NR_EVT AND  I.CD_ATB IN(504, 505, 798, 800, 1043, 1126, 1166, 1207)) -- PREFIXO DEMANDANTE
	LEFT JOIN fluxoTrabalho.ctu_atb_evt M ON(M.CD_SUB_PROJ = A.CD_SUB_PROJ AND M.AA_EVT = A.AA_EVT AND M.NR_EVT = A.NR_EVT AND  M.CD_ATB IN(385))  -- ENQUADRAMENTO LEGAL
	LEFT JOIN fluxoTrabalho.ls_opc_atb N ON(N.NR_SEQL_LS_OPC = M.VL_ATB_EVT_INT AND M.CD_ATB = N.CD_ATB AND N.CD_SUB_PROJ = M.CD_SUB_PROJ  )
    LEFT JOIN fluxoTrabalho.ctu_atb_evt P ON(P.CD_SUB_PROJ = A.CD_SUB_PROJ AND P.AA_EVT = A.AA_EVT AND P.NR_EVT = A.NR_EVT AND P.CD_ATB IN(175, 427, 496)) -- RESULTADO FINAL DO PROCESSO
    LEFT JOIN fluxoTrabalho.ls_opc_atb Q ON(Q.NR_SEQL_LS_OPC = P.VL_ATB_EVT_INT AND Q.CD_ATB = P.CD_ATB  AND P.CD_SUB_PROJ = Q.CD_SUB_PROJ ) -- RESPONS PROCESSO
	LEFT JOIN mstNovo.depe E ON(E.CD_PRF = I.VL_ATB_EVT_INT AND E.CD_SBDD = 0)
	LEFT JOIN mstNovo.depe_jrdc K ON(K.CD_UOR_JRDD = E.CD_UOR AND K.CD_JRDC = 2819)
	LEFT JOIN mstNovo.depe L ON(L.CD_UOR = K.CD_UOR_JRDT)
	LEFT JOIN mstNovo.depe_jrdc F ON(F.CD_UOR_JRDD = E.CD_UOR AND F.CD_JRDC = 1200)
	LEFT JOIN mstNovo.depe G ON(G.CD_UOR = F.CD_UOR_JRDT)
	LEFT JOIN arh_dipes.arhfot01 H ON(H.matricula = A.CD_USU_CRIC_EVT)
    LEFT JOIN mstNovo.depe O ON(O.CD_PRF = I.VL_ATB_EVT_INT AND O.CD_SBDD = 0)  
    LEFT JOIN mstNovo.depe P ON(P.CD_PRF = I.VL_ATB_EVT_INT AND P.CD_SBDD = 0) 
    LEFT JOIN mstNovo.depe_jrdc Q ON(Q.CD_UOR_JRDD = P.CD_UOR AND Q.CD_JRDC = 1220)
    LEFT JOIN mstNovo.depe R ON(R.CD_UOR = Q.CD_UOR_JRDT)
    LEFT JOIN fluxoTrabalho.ctu_atb_evt S ON(S.CD_SUB_PROJ = A.CD_SUB_PROJ AND S.AA_EVT = A.AA_EVT AND S.NR_EVT = A.NR_EVT AND S.CD_ATB IN(653, 654, 655, 656, 657, 1154, 1169, 1209))  -- SINISTRO
    LEFT JOIN fluxoTrabalho.ls_opc_atb T ON(T.NR_SEQL_LS_OPC = S.VL_ATB_EVT_INT AND T.CD_ATB = S.CD_ATB)
   
	WHERE 
	DATE(A.TS_CRIC_EVT) BETWEEN @INI_CMP AND @FIM_CMP
	AND A.CD_SUB_PROJ IN (117, 217, 68, 69, 74, 215, 216, 219, 220, 212, 214, 225, 213, 210, 211, 238, 363)
	AND I.VL_ATB_EVT_INT > 0
	AND A.CD_FASE_EVT NOT IN(5, 6)   -- FASES DO EVENTO DIFERENTE DE CANCELADO E DEVOLVIDO
	AND (T.TX_LS_OPC_ATB = 'NÃO' OR T.TX_LS_OPC_ATB IS NULL)  -- EXCLUSÃO DE SINISTRADOS
	AND NOT(A.AA_EVT_PAI > 0 AND A.NR_EVT_PAI > 0) -- EXCLUSÃO DE CLONES
    -- De acordo com o evento 2019/148165, foi solicitado que o evento 2019/144628 fosse retirado por se tratar de SINISTRO, e não estar classificado como tal.
    AND A.NR_EVT != 144628 
        
    -- 147199
    
	GROUP BY CD_SUB_PROJ, AA_EVT, NR_EVT, I.VL_ATB_EVT_INT
    
UNION 

	SELECT DISTINCT 
		A.CD_SUB_PROJ,
		A.AA_EVT, 
		A.NR_EVT, 
		A.TX_EVT,
		A.CD_FASE_EVT, 
		A.CD_PRF_EXEC, 
		I.VL_ATB_EVT_INT AS PRF_DEMAND, 
		O.NM_UOR_RED AS DEMAND,
		L.CD_PRF AS PRF_CESUP_REDE, 
		L.NM_UOR_RED AS CESUP_REDE,
		9903 AS PRF_DIR,
		'DITEC-TECNOLOGIA    ' AS DIRETORIA,
		8033 AS PRF_VP, 
		'VITEC' AS VP,
		DATE(A.TS_CRIC_EVT) AS DT_CRIC_EVT,
		A.CD_USU_CRIC_EVT, 
		H.prefixo_lotacao AS PRF_USU_CRIC,
		A.DT_INC_EVT, 
		A.DT_FIM_EVT, 
		P.VL_ATB_EVT_INT AS CD_RES_PROC,
		Q.TX_LS_OPC_ATB AS RES_PROC,
		M.VL_ATB_EVT_INT,
		N.TX_LS_OPC_ATB AS EQD_LGAL,
         T.TX_LS_OPC_ATB AS SINISTRO,
		B.VL_ATB_EVT_DT AS DT_LIM , 
		C.VL_ATB_EVT_INT AS PZ_ETGA, 
		D.VL_ATB_EVT_INT AS PZ_AVL, 
		CASE 
			-- ALTERAÇÃO SOLICITADA POR DICAD DEMANDA 2019/144833 - INÍCIO
			-- WHEN A.CD_SUB_PROJ IN(117, 216, 217) THEN 26
			WHEN A.CD_SUB_PROJ IN(216) THEN 26  										
			WHEN A.CD_SUB_PROJ IN(117, 217) THEN 15
			-- ALTERAÇÃO SOLICITADA POR DICAD DEMANDA 2019/144833 - FIM
			WHEN A.CD_SUB_PROJ IN(68, 69, 73, 74, 208, 215, 218, 219, 220, 222) THEN 30
			WHEN A.CD_SUB_PROJ IN (212, 214, 225) THEN 33
			WHEN A.CD_SUB_PROJ IN (213) THEN 43
			WHEN A.CD_SUB_PROJ IN(210, 211, 238, 363) THEN 132
		END AS PZ_IND,      -- PRAZO DE LICITAÇÃO POR SUBPROJETO EM DIAS
		CASE 
			WHEN A.CD_SUB_PROJ IN(68, 69, 73, 74, 92, 115, 117, 169, 208, 213, 214, 215, 216, 217, 218, 219, 220,221, 222, 223, 224) THEN 1
			WHEN A.CD_SUB_PROJ IN (210, 211, 238, 363) THEN 1.5
			WHEN A.CD_SUB_PROJ IN (212, 225) THEN 2
		END AS PESO_IND     -- PESO DO INDICADOR POR SUBPROJETO EM DIAS


		FROM fluxoTrabalho.evt A

		LEFT JOIN fluxoTrabalho.ctu_atb_evt B ON(B.CD_SUB_PROJ = A.CD_SUB_PROJ AND B.AA_EVT = A.AA_EVT AND B.NR_EVT = A.NR_EVT AND B.CD_ATB IN(407, 441, 444, 447, 456, 457, 460, 463, 466, 469, 472, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530))  -- DATA LIMITE
		LEFT JOIN fluxoTrabalho.ctu_atb_evt C ON(C.CD_SUB_PROJ = A.CD_SUB_PROJ AND C.AA_EVT = A.AA_EVT AND C.NR_EVT = A.NR_EVT AND C.CD_ATB IN(406, 442, 445, 448, 452, 454, 458, 461, 464, 467, 470, 473))  -- PRAZO DE ENTREGA
		LEFT JOIN fluxoTrabalho.ctu_atb_evt D ON(D.CD_SUB_PROJ = A.CD_SUB_PROJ AND D.AA_EVT = A.AA_EVT AND D.NR_EVT = A.NR_EVT AND D.CD_ATB IN(410, 443, 446, 449, 453, 455, 459, 462, 465, 468, 471, 474))    -- PRAZO AVALIACAO
		LEFT JOIN fluxoTrabalho.ctu_atb_evt I ON(I.CD_SUB_PROJ = A.CD_SUB_PROJ AND I.AA_EVT = A.AA_EVT AND I.NR_EVT = A.NR_EVT AND  I.CD_ATB IN(504, 505, 798, 800, 1043, 1126, 1166, 1207)) -- PREFIXO DEMANDANTE
		LEFT JOIN fluxoTrabalho.ctu_atb_evt M ON(M.CD_SUB_PROJ = A.CD_SUB_PROJ AND M.AA_EVT = A.AA_EVT AND M.NR_EVT = A.NR_EVT AND  M.CD_ATB IN(385))  -- ENQUADRAMENTO LEGAL
		LEFT JOIN fluxoTrabalho.ls_opc_atb N ON(N.NR_SEQL_LS_OPC = M.VL_ATB_EVT_INT AND M.CD_ATB = N.CD_ATB AND N.CD_SUB_PROJ = M.CD_SUB_PROJ  )
        -- LEFT JOIN fluxoTrabalho.ls_opc_atb N ON(N.NR_SEQL_LS_OPC = M.VL_ATB_EVT_INT AND M.CD_ATB = N.CD_ATB)
		LEFT JOIN fluxoTrabalho.ctu_atb_evt P ON(P.CD_SUB_PROJ = A.CD_SUB_PROJ AND P.AA_EVT = A.AA_EVT AND P.NR_EVT = A.NR_EVT AND P.CD_ATB IN(175, 427, 496)) -- RESULTADO FINAL DO PROCESSO
		LEFT JOIN fluxoTrabalho.ls_opc_atb Q ON(Q.NR_SEQL_LS_OPC = P.VL_ATB_EVT_INT AND Q.CD_ATB = P.CD_ATB  AND P.CD_SUB_PROJ = Q.CD_SUB_PROJ ) -- RESPONS PROCESSO
		LEFT JOIN mstNovo.depe E ON(E.CD_PRF = I.VL_ATB_EVT_INT AND E.CD_SBDD = 0)
		LEFT JOIN mstNovo.depe_jrdc K ON(K.CD_UOR_JRDD = E.CD_UOR AND K.CD_JRDC = 2819)
		LEFT JOIN mstNovo.depe L ON(L.CD_UOR = K.CD_UOR_JRDT)
		LEFT JOIN mstNovo.depe_jrdc F ON(F.CD_UOR_JRDD = E.CD_UOR AND F.CD_JRDC = 1200)
		LEFT JOIN mstNovo.depe G ON(G.CD_UOR = F.CD_UOR_JRDT)
		LEFT JOIN arh_dipes.arhfot01 H ON(H.matricula = A.CD_USU_CRIC_EVT)
		LEFT JOIN mstNovo.depe O ON(O.CD_PRF = I.VL_ATB_EVT_INT AND O.CD_SBDD = 0)  
		LEFT JOIN mstNovo.depe P ON(P.CD_PRF = I.VL_ATB_EVT_INT AND P.CD_SBDD = 0) 
		LEFT JOIN mstNovo.depe_jrdc Q ON(Q.CD_UOR_JRDD = P.CD_UOR AND Q.CD_JRDC = 1220)
		LEFT JOIN mstNovo.depe R ON(R.CD_UOR = Q.CD_UOR_JRDT)
        LEFT JOIN fluxoTrabalho.ctu_atb_evt S ON(S.CD_SUB_PROJ = A.CD_SUB_PROJ AND S.AA_EVT = A.AA_EVT AND S.NR_EVT = A.NR_EVT AND S.CD_ATB IN(653, 654, 655, 656, 657, 1154, 1169, 1209))  -- SINISTRO
        LEFT JOIN fluxoTrabalho.ls_opc_atb T ON(T.NR_SEQL_LS_OPC = S.VL_ATB_EVT_INT AND T.CD_ATB = S.CD_ATB)
	   
		WHERE 
		DATE(A.TS_CRIC_EVT) BETWEEN @INI_CMP AND @FIM_CMP
		AND A.CD_SUB_PROJ IN (117, 217, 68, 69, 74, 215, 216, 219, 220, 212, 214, 225, 213, 210, 211, 238, 363)
		AND I.VL_ATB_EVT_INT > 0
		AND A.CD_FASE_EVT NOT IN(5, 6)     -- FASES DO EVENTO DIFERENTE DE CANCELADO E DEVOLVIDO
		AND I.VL_ATB_EVT_INT = 8969
		AND (T.TX_LS_OPC_ATB = 'NÃO' OR T.TX_LS_OPC_ATB IS NULL) -- EXCLUSÃO DE SINITRADOS
        AND NOT(A.AA_EVT_PAI > 0 AND A.NR_EVT_PAI > 0) -- EXCLUSÃO DE CLONES
		-- De acordo com o evento 2019/148165, foi solicitado que o evento 2019/144628 fosse retirado por se tratar de SINISTRO, e não estar classificado como tal.
		AND A.NR_EVT != 144628

    
	GROUP BY CD_SUB_PROJ, AA_EVT, NR_EVT, I.VL_ATB_EVT_INT;

# EXTRAÇÃO DE EVENTOS PARA APURAÇÃO DO INDICADOR PDCON
/*DROP TABLE IF EXISTS gac.PDCON_BASE ;
CREATE TABLE gac.PDCON_BASE*/

DELETE FROM gac.PDCON_BASE /*WHERE DT_CRIC_EVT BETWEEN @INI_CMP AND @FIM_CMP*/;
INSERT INTO gac.PDCON_BASE
SELECT 
Z.CD_SUB_PROJ, 
Z.AA_EVT, 
Z.NR_EVT, 
Z.TX_EVT, 
Z.CD_FASE_EVT, 
Z.CD_PRF_EXEC, 
Y.PRF_DEMAND, 
Y.DEMAND,
Y.PRF_CESUP_REDE, 
Y.CESUP_REDE,
Y.PRF_DIR,
Y.DIRETORIA,
Y.PRF_VP, 
Y.VP,
Y.DT_CRIC_EVT,
Y.CD_USU_CRIC_EVT, 
Y.PRF_USU_CRIC,
Y.DT_INC_EVT, 
Y.DT_FIM_EVT, 
Y.CD_RES_PROC,
Y.RES_PROC,
Y.VL_ATB_EVT_INT,
Y.EQD_LGAL,
Y.SINISTRO,
Y.DT_LIM , 
Y.PZ_ETGA, 
Y.PZ_AVL, 
Y.PZ_IND,
Y.PESO_IND
FROM fluxoTrabalho.evt Z

LEFT JOIN  fluxoAux.PDCON_FILTRADO Y
ON(Y.CD_SUB_PROJ = Z.CD_SUB_PROJ AND Y.AA_EVT = Z.AA_EVT AND Y.NR_EVT = Z.NR_EVT)

 WHERE DATE(Z.TS_CRIC_EVT) BETWEEN @INI_CMP AND @FIM_CMP
AND Z.CD_SUB_PROJ IN (117, 217, 68, 69, 74, 215, 216, 219, 220, 212, 214, 225, 213, 210, 211, 238, 363)
AND Z.CD_PRF_EXEC IN(8558, 7421)
AND Z.CD_FASE_EVT NOT IN(5, 6)
AND Y.PRF_DEMAND IS NOT NULL
 ;   


-- EVENTOS QUE CONTÉM O ATRIBUTO RES_PROC = DEVOLVIDO OU CANCELADO    
DROP TABLE IF EXISTS gac.PDCON_ATB_AUX;
CREATE TABLE gac.PDCON_ATB_AUX
SELECT 
*
FROM gac.PDCON_BASE
WHERE ((CD_RES_PROC = 2 AND CD_SUB_PROJ IN(60, 64, 115, 169, 197, 198, 199, 175, 155, 200, 208, 210, 211, 213, 214, 212, 225, 156, 233, 234, 235))
OR (CD_RES_PROC = 5 AND CD_SUB_PROJ IN(68, 69, 70, 71, 74, 62, 63, 64, 65, 66, 194))
OR (CD_RES_PROC = 1196 AND CD_SUB_PROJ IN(218))
OR (CD_RES_PROC = 1357 AND CD_SUB_PROJ IN(215))
OR (CD_RES_PROC = 1448 AND CD_SUB_PROJ IN(224))
OR (CD_RES_PROC = 1707 AND CD_SUB_PROJ IN(238))
OR (CD_SUB_PROJ IN(92, 118, 116, 117, 222, 232, 219) AND CD_RES_PROC = 2)
OR (CD_SUB_PROJ IN(72, 73, 60, 61, 115, 169, 175, 155, 200, 208, 210, 211, 213, 214, 212, 225, 156, 233, 234, 235) AND CD_RES_PROC = 5)
OR (CD_SUB_PROJ IN(68, 69, 70, 71, 74) AND CD_RES_PROC = 6)
OR (CD_SUB_PROJ IN(62, 63, 64, 65, 66) AND CD_RES_PROC = 8)
OR (CD_SUB_PROJ IN(1199) AND CD_RES_PROC = 218) 
OR (CD_SUB_PROJ IN(1360) AND CD_RES_PROC = 215)
OR (CD_SUB_PROJ IN(1451) AND CD_RES_PROC = 224)
OR (CD_SUB_PROJ IN(1537) AND CD_RES_PROC = 220)
OR (CD_SUB_PROJ IN(1710) AND CD_RES_PROC = 238)
OR (CD_SUB_PROJ IN(1894) AND CD_RES_PROC = 221))
;

-- TABLE SEM EXCLUSÃO DE EVENTOS DEVOLVIDOS OU CANCELADOS 
DROP TABLE IF EXISTS gac.PDCON1;
CREATE TABLE gac.PDCON1
SELECT A.* 
FROM  gac.PDCON_BASE A
LEFT JOIN gac.PDCON_ATB_AUX Z ON (Z.AA_EVT = A.AA_EVT AND Z.NR_EVT = A.NR_EVT AND Z.CD_SUB_PROJ = A.CD_SUB_PROJ)
WHERE Z.CD_SUB_PROJ IS NULL;


-- EXCLUSÃO DE ENQUADRAMENTO LEGAL EMERGENCIAL SEM DEVOLVIDOS E CANCELADOS
DROP TABLE IF EXISTS gac.PDCON_SDC;
CREATE TABLE gac.PDCON_SDC
	SELECT * 
	FROM gac.PDCON1
	WHERE NR_EVT NOT IN(SELECT NR_EVT 
						FROM gac.PDCON1
						WHERE CD_SUB_PROJ IN(212, 61) AND VL_ATB_EVT_INT = 2);
                        
                  
-- EXCLUSÃO DE ENQUEADRAMENTO LEGAL EMERGENCIAL COM DEVOLVIDOS E CANCELADOS                  
DROP TABLE IF EXISTS gac.PDCON_CDC;
CREATE TABLE gac.PDCON_CDC
	SELECT * 
	FROM gac.PDCON_BASE
	WHERE NR_EVT NOT IN(SELECT NR_EVT 
						FROM gac.PDCON1
						WHERE CD_SUB_PROJ IN(212, 61) AND VL_ATB_EVT_INT = 2);

                        
-- INCLUSÃO DE CAMPO COM CÁLCULOS TABLE SEM DEVOLVIDOS E CANCELADOS
DROP TABLE IF EXISTS gac.PDCON_AUX_SDC;
CREATE TABLE gac.PDCON_AUX_SDC
SELECT
A.CD_SUB_PROJ,	
A.AA_EVT, 	
A.NR_EVT, 	
A.CD_FASE_EVT, 	
A.TX_EVT,	
A.CD_PRF_EXEC, 	
A.PRF_DEMAND,	
A.DEMAND,	
A.PRF_VP, 	
A.VP,	
A.PRF_DIR,	
A.DIRETORIA,	
A.PRF_CESUP_REDE,
A.CESUP_REDE, 	
A.DT_CRIC_EVT,	
A.CD_USU_CRIC_EVT, 	
A.PRF_USU_CRIC, 	
A.DT_INC_EVT, 	
A.DT_FIM_EVT, 	
A.CD_RES_PROC,	
A.RES_PROC,	
A.DT_LIM,	
A.PZ_ETGA, 	
A.PZ_AVL, 	
A.PZ_IND, 	
A.PESO_IND,
A.DATA_PRV,
B.CD_ATB, 
B.VL_ATB_EVT_INT, 
C.TX_LS_OPC_ATB, 
CASE 
	WHEN C.TX_LS_OPC_ATB = 'DISEC' AND PRF_DIR = 8558 AND PRF_DEMAND = 8969 THEN 0
    WHEN C.TX_LS_OPC_ATB = 'DITEC' AND PRF_DIR = 9903 AND PRF_DEMAND = 8969 THEN 0
    WHEN C.TX_LS_OPC_ATB = 'Demandante' THEN 0
    ELSE A.DIF_DIAS
END AS DIF_DIAS, 
A.EQD_LGAL,
A.SINISTRO

FROM 
	(SELECT DISTINCT A.CD_SUB_PROJ,	A.AA_EVT, 	A.NR_EVT, 	A.CD_FASE_EVT, 	A.TX_EVT,	A.CD_PRF_EXEC, 	A.PRF_DEMAND,	A.DEMAND,	A.PRF_VP, 	A.VP,	A.PRF_DIR,	A.DIRETORIA,	A.PRF_CESUP_REDE,
	A.CESUP_REDE, 	A.DT_CRIC_EVT,	A.CD_USU_CRIC_EVT, 	A.PRF_USU_CRIC, 	A.DT_INC_EVT, 	A.DT_FIM_EVT, 	A.CD_RES_PROC,	A.RES_PROC,	A.DT_LIM,	A.PZ_ETGA, 	A.PZ_AVL, 	A.PZ_IND, 	A.PESO_IND,
	DATE_ADD(A.DT_CRIC_EVT, INTERVAL (ifnull(PZ_IND, 0) + IFNULL(PZ_ETGA, 0) + IFNULL(PZ_AVL,0)) DAY) AS DATA_PRV,
	CASE 
		WHEN A.DT_LIM IS NULL THEN DATEDIFF((DATE_ADD(A.DT_CRIC_EVT, INTERVAL (ifnull(PZ_IND, 0) + IFNULL(PZ_ETGA, 0) + IFNULL(PZ_AVL,0)) DAY)),(DATE_ADD(A.DT_CRIC_EVT, INTERVAL (ifnull(PZ_IND, 0) + IFNULL(PZ_ETGA, 0) + IFNULL(PZ_AVL,0)) DAY)))
		ELSE DATEDIFF(A.DT_LIM,(DATE_ADD(A.DT_CRIC_EVT, INTERVAL (ifnull(PZ_IND, 0) + IFNULL(PZ_ETGA, 0) + IFNULL(PZ_AVL,0)) DAY))) 
	END AS DIF_DIAS, A.EQD_LGAL, A.SINISTRO
	FROM gac.PDCON_SDC A
	WHERE PRF_DEMAND > 0) A
    
LEFT JOIN fluxoTrabalho.ctu_atb_evt B ON(B.CD_SUB_PROJ = A.CD_SUB_PROJ AND B.AA_EVT = A.AA_EVT AND B.NR_EVT = A.NR_EVT 
										AND B.CD_ATB IN(1037, 1039, 1053, 1055, 1057, 1059, 1061, 1065, 1067, 1069, 1071, 1073, 1075, 1077, 1079, 1083, 1085, 1087, 1089, 1091, 1093 ,1095, 1097, 1099, 1101))
LEFT JOIN fluxoTrabalho.ls_opc_atb C ON(C.NR_SEQL_LS_OPC = B.VL_ATB_EVT_INT)

ORDER BY A.CD_SUB_PROJ, A.AA_EVT, A.NR_EVT, A.PRF_DEMAND, A.PRF_DIR;


-- INCLUSÃO DE CAMPO COM CÁLCULOS TABLE COM DEVOLVIDOS E CANCELADOS
DROP TABLE IF EXISTS gac.PDCON_AUX_CDC;
CREATE TABLE gac.PDCON_AUX_CDC AS 

SELECT
A.CD_SUB_PROJ,	
A.AA_EVT, 	
A.NR_EVT, 	
A.CD_FASE_EVT, 	
A.TX_EVT,	
A.CD_PRF_EXEC, 	
A.PRF_DEMAND,	
A.DEMAND,	
A.PRF_VP, 	
A.VP,	
A.PRF_DIR,	
A.DIRETORIA,	
A.PRF_CESUP_REDE,
A.CESUP_REDE, 	
A.DT_CRIC_EVT,	
A.CD_USU_CRIC_EVT, 	
A.PRF_USU_CRIC, 	
A.DT_INC_EVT, 	
A.DT_FIM_EVT, 	
A.CD_RES_PROC,	
A.RES_PROC,	
A.DT_LIM,	
A.PZ_ETGA, 	
A.PZ_AVL, 	
A.PZ_IND, 	
A.PESO_IND,
A.DATA_PRV,
B.CD_ATB, 
B.VL_ATB_EVT_INT, 
C.TX_LS_OPC_ATB, 
CASE 
	WHEN C.TX_LS_OPC_ATB = 'DISEC' AND PRF_DIR = 8558 AND PRF_DEMAND = 8969 THEN 0
    WHEN C.TX_LS_OPC_ATB = 'DITEC' AND PRF_DIR = 9903 AND PRF_DEMAND = 8969 THEN 0
    WHEN C.TX_LS_OPC_ATB = 'Demandante' THEN 0
    ELSE A.DIF_DIAS
END AS DIF_DIAS,
A.EQD_LGAL, 
A.SINISTRO,
K.TX_LS_OPC_ATB AS ITEM_SUPRIMENTO

FROM (SELECT DISTINCT A.CD_SUB_PROJ,A.AA_EVT, A.NR_EVT, A.CD_FASE_EVT, A.TX_EVT,A.CD_PRF_EXEC, A.PRF_DEMAND,A.DEMAND,A.PRF_VP, A.VP,A.PRF_DIR,A.DIRETORIA,A.PRF_CESUP_REDE,A.CESUP_REDE,A.DT_CRIC_EVT,
						A.CD_USU_CRIC_EVT, A.PRF_USU_CRIC, A.DT_INC_EVT, A.DT_FIM_EVT, A.CD_RES_PROC,A.RES_PROC,A.DT_LIM,A.PZ_ETGA, A.PZ_AVL, A.PZ_IND, A.PESO_IND,
						DATE_ADD(A.DT_CRIC_EVT, INTERVAL (ifnull(PZ_IND, 0) + IFNULL(PZ_ETGA, 0) + IFNULL(PZ_AVL,0)) DAY) AS DATA_PRV,
						CASE 
							WHEN A.DT_LIM IS NULL THEN DATEDIFF((DATE_ADD(A.DT_CRIC_EVT, INTERVAL (ifnull(PZ_IND, 0) + IFNULL(PZ_ETGA, 0) + IFNULL(PZ_AVL,0)) DAY)),(DATE_ADD(A.DT_CRIC_EVT, INTERVAL (ifnull(PZ_IND, 0) + IFNULL(PZ_ETGA, 0) + IFNULL(PZ_AVL,0)) DAY)))
							ELSE DATEDIFF(A.DT_LIM,(DATE_ADD(A.DT_CRIC_EVT, INTERVAL (ifnull(PZ_IND, 0) + IFNULL(PZ_ETGA, 0) + IFNULL(PZ_AVL,0)) DAY))) 
						END AS DIF_DIAS, A.EQD_LGAL, A.SINISTRO
		FROM gac.PDCON_CDC A
		WHERE PRF_DEMAND > 0) A
LEFT JOIN fluxoTrabalho.ctu_atb_evt B ON(B.CD_SUB_PROJ = A.CD_SUB_PROJ AND B.AA_EVT = A.AA_EVT AND B.NR_EVT = A.NR_EVT 
										AND B.CD_ATB IN(1037, 1039, 1053, 1055, 1057, 1059, 1061, 1065, 1067, 1069, 1071, 1073, 1075, 1077, 1079, 1083, 1085, 1087, 1089, 1091, 1093 ,1095, 1097, 1099, 1101))
LEFT JOIN fluxoTrabalho.ls_opc_atb C ON(C.NR_SEQL_LS_OPC = B.VL_ATB_EVT_INT)

LEFT JOIN fluxoTrabalho.ctu_atb_evt J ON(J.AA_EVT = A.AA_EVT AND J.NR_EVT = A.NR_EVT AND J.CD_SUB_PROJ = A.CD_SUB_PROJ AND J.CD_ATB IN(154, 413, 490, 553, 665, 791, 1129, 1161)) -- Item de Suprimento
LEFT JOIN fluxoTrabalho.ls_opc_atb K ON(K.CD_SUB_PROJ = A.CD_SUB_PROJ AND K.CD_ATB = J.CD_ATB AND K.NR_SEQL_LS_OPC = J.VL_ATB_EVT_INT)


ORDER BY A.CD_SUB_PROJ, A.AA_EVT, A.NR_EVT, A.PRF_DEMAND, A.PRF_DIR
;

-- PREFIXO DEMANDANTE CESUP SEM DEVOLVIDOS OU CANCELADOS
DROP TABLE IF EXISTS gac.PDCON_AUX2_SDC ;
CREATE TABLE gac.PDCON_AUX2_SDC 
SELECT * FROM gac.PDCON_AUX_SDC WHERE PRF_DEMAND IN(9091, 9093, 7425, 7422, 9099, 7423, 7418, 7420, 7427);

-- PREFIXO DEMANDANTE CESUP COM DEVOLVIDOS OU CANCELADOS
DROP TABLE IF EXISTS gac.PDCON_AUX2_CDC ;
CREATE TABLE gac.PDCON_AUX2_CDC 
SELECT * FROM gac.PDCON_AUX_CDC WHERE PRF_DEMAND IN(9091, 9093, 7425, 7422, 9099, 7423, 7418, 7420, 7427);




/*******************************GAC 01 ********************************/

DROP TABLE IF EXISTS gac.PADCON_GAC1;
CREATE TABLE gac.PADCON_GAC1
SELECT                                                 -- PREFIXO DEMANDANTE
	1 AS cd_bloc, 
    177 AS cd_in, 
	A.PRF_DEMAND as cd_prf_depe,
/*    A.PRF_CESUP_REDE,
    B.*,*/
    @ANO_REF as ano_ref,  
	@MES_REF as mes_ref, 
	DATEDIFF(CURDATE(), 19600101) as dt_prct,
	-- COUNT(A.PRF_DEMAND) AS TOTAL , 
    -- IFNULL(B.ATRASADOS,0) AS ATRASADOS,
    ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) AS pc_rstd,
    CASE
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.9501 AND 1.0000 THEN 10.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.9001 AND 0.9500 THEN 9.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.8501 AND 0.9000 THEN 8.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.8001 AND 0.8500 THEN 7.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.7001 AND 0.8000 THEN 6.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.6001 AND 0.7000 THEN 5.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.3001 AND 0.6000 THEN 4.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.0001 AND 0.3000 THEN 3.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN -0.5099 AND 0.0000 THEN 2.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN -1.0000 AND -0.5100 THEN 1.0000
	END AS cd_rstd,
	QUOTE(concat('PERÍODO DE APURAÇÃO: ', @INI_CMP, ' A ', @FIM_CMP)) as tx_jst_rstd

FROM gac.PDCON_AUX_SDC A
LEFT JOIN (

SELECT A.PRF_DIR, A.PRF_DEMAND, IFNULL(B.ATRASADOS,0) AS ATRASADOS 
FROM 
gac.PDCON_AUX_SDC A  

LEFT JOIN (SELECT PRF_DIR, PRF_DEMAND, SUM(PESO_IND) AS ATRASADOS FROM gac.PDCON_AUX_SDC WHERE DIF_DIAS < 0   GROUP BY PRF_DEMAND, PRF_DIR) B on (A.PRF_DEMAND = B.PRF_DEMAND AND A.PRF_DIR = B.PRF_DIR)
GROUP BY A.PRF_DEMAND, PRF_DIR

) B ON(B.PRF_DEMAND = A.PRF_DEMAND)
WHERE A.PRF_DEMAND IS NOT NULL AND (A.PRF_DEMAND <> B.PRF_DIR AND A.PRF_DEMAND <> A.PRF_CESUP_REDE) 

GROUP BY A.PRF_DEMAND



UNION



SELECT                                             -- CESUP
	1 AS cd_bloc, 
    177 AS cd_in, 
	A.PRF_CESUP_REDE as cd_prf_depe,
    @ANO_REF as ano_ref,  
	@MES_REF as mes_ref, 
	DATEDIFF(CURDATE(), 19600101) as dt_prct,
    ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) AS pc_rstd,
    CASE
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.9501 AND 1.0000 THEN 10.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.9001 AND 0.9500 THEN 9.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.8501 AND 0.9000 THEN 8.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.8001 AND 0.8500 THEN 7.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.7001 AND 0.8000 THEN 6.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.6001 AND 0.7000 THEN 5.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.3001 AND 0.6000 THEN 4.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.0001 AND 0.3000 THEN 3.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN -0.5099 AND 0.0000 THEN 2.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN -1.0000 AND -0.5100 THEN 1.0000
	END AS cd_rstd,
    QUOTE(concat('PERÍODO DE APURAÇÃO: ', @INI_CMP, ' A ', @FIM_CMP)) as tx_jst_rstd
FROM gac.PDCON_AUX2_SDC A
LEFT JOIN (SELECT PRF_CESUP_REDE, SUM(PESO_IND) AS ATRASADOS FROM gac.PDCON_AUX2_SDC  WHERE DIF_DIAS < 0 GROUP BY PRF_CESUP_REDE) B
ON(B.PRF_CESUP_REDE = A.PRF_CESUP_REDE)

WHERE A.PRF_CESUP_REDE IS NOT NULL

GROUP BY A.PRF_CESUP_REDE

UNION

SELECT                                     -- DIRETORIA
	1 AS cd_bloc, 
    177 AS cd_in, 
	A.PRF_DIR as cd_prf_depe,
    @ANO_REF as ano_ref,  
	@MES_REF as mes_ref, 
	DATEDIFF(CURDATE(), 19600101) as dt_prct,
    ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) AS pc_rstd,
    CASE
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.9501 AND 1.0000 THEN 10.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.9001 AND 0.9500 THEN 9.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.8501 AND 0.9000 THEN 8.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.8001 AND 0.8500 THEN 7.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.7001 AND 0.8000 THEN 6.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.6001 AND 0.7000 THEN 5.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.3001 AND 0.6000 THEN 4.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.0001 AND 0.3000 THEN 3.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN -0.5099 AND 0.0000 THEN 2.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN -1.0000 AND -0.5100 THEN 1.0000
	END AS cd_rstd,
	QUOTE(concat('PERÍODO DE APURAÇÃO: ', @INI_CMP, ' A ', @FIM_CMP)) as tx_jst_rstd
FROM gac.PDCON_AUX_SDC A
LEFT JOIN (SELECT PRF_DIR, SUM(PESO_IND) AS ATRASADOS FROM gac.PDCON_AUX_SDC  WHERE DIF_DIAS < 0 GROUP BY PRF_DIR) B
ON(B.PRF_DIR = A.PRF_DIR)

WHERE A.PRF_DIR IS NOT NULL

GROUP BY A.PRF_DIR


UNION 

SELECT                                     -- VP
	1 AS cd_bloc, 
    177 AS cd_in, 
	A.PRF_VP as cd_prf_depe,
    @ANO_REF as ano_ref,  
	@MES_REF as mes_ref, 
	DATEDIFF(CURDATE(), 19600101) as dt_prct,
    ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) AS pc_rstd,
    CASE
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.9501 AND 1.0000 THEN 10.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.9001 AND 0.9500 THEN 9.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.8501 AND 0.9000 THEN 8.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.8001 AND 0.8500 THEN 7.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.7001 AND 0.8000 THEN 6.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.6001 AND 0.7000 THEN 5.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.3001 AND 0.6000 THEN 4.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.0001 AND 0.3000 THEN 3.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN -0.5099 AND 0.0000 THEN 2.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN -1.0000 AND -0.5100 THEN 1.0000
	END AS cd_rstd,
	QUOTE(concat('PERÍODO DE APURAÇÃO: ', @INI_CMP, ' A ', @FIM_CMP)) as tx_jst_rstd
FROM gac.PDCON_AUX_SDC A
LEFT JOIN (SELECT PRF_VP, SUM(PESO_IND) AS ATRASADOS FROM gac.PDCON_AUX_SDC  WHERE DIF_DIAS < 0 GROUP BY PRF_VP) B
ON(B.PRF_VP = A.PRF_VP)
WHERE A.PRF_VP = 8166

GROUP BY A.PRF_VP

/*UNION 

SELECT                                     -- VP
	1 AS cd_bloc, 
    177 AS cd_in, 
	A.PRF_VP as cd_prf_depe,
    @ANO_REF as ano_ref,  
	@MES_REF as mes_ref, 
	DATEDIFF(CURDATE(), 19600101) as dt_prct,
    ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) AS pc_rstd,
    CASE
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.9501 AND 1.0000 THEN 10.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.9001 AND 0.9500 THEN 9.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.8501 AND 0.9000 THEN 8.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.8001 AND 0.8500 THEN 7.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.7001 AND 0.8000 THEN 6.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.6001 AND 0.7000 THEN 5.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.3001 AND 0.6000 THEN 4.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN 0.0001 AND 0.3000 THEN 3.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN -0.5099 AND 0.0000 THEN 2.0000
		WHEN ROUND(1 - (IFNULL(B.ATRASADOS, 0) / COUNT(A.PRF_DEMAND)),4) BETWEEN -1.0000 AND -0.5100 THEN 1.0000
	END AS cd_rstd,
	QUOTE(concat('PERÍODO DE APURAÇÃO: ', @INI_CMP, ' A ', @FIM_CMP)) as tx_jst_rstd
FROM gac.PDCON_AUX_SDC A
LEFT JOIN (SELECT PRF_VP, SUM(PESO_IND) AS ATRASADOS FROM gac.PDCON_AUX_SDC  WHERE DIF_DIAS < 0 GROUP BY PRF_VP) B
ON(B.PRF_VP = A.PRF_VP)
WHERE A.PRF_VP IS NOT NULL
*/
;


/******************************* GAC2  *****************************************/

DROP TABLE IF EXISTS gac.PADCON_GAC2;
CREATE TABLE gac.PADCON_GAC2

SELECT DISTINCT                                                    -- DEMANDANTE
    127 AS cd_vrv, 													-- QT PROCESSOS PROTOCOLADOS                                              
    A.PRF_DEMAND AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.PRF_DEMAND) AS vl_vrv,
    177 AS cd_in
FROM
    gac.PDCON_AUX_CDC A
        LEFT JOIN (SELECT PRF_DIR, PRF_DEMAND, SUM(PESO_IND) AS ATRASADOS FROM gac.PDCON_AUX WHERE DIF_DIAS < 0 GROUP BY PRF_DEMAND) B 
        ON (B.PRF_DEMAND = A.PRF_DEMAND)

	WHERE  A.PRF_DEMAND IS NOT NULL
	AND (A.PRF_DEMAND <> B.PRF_DIR
	AND A.PRF_DEMAND <>  A.PRF_CESUP_REDE)
GROUP BY A.PRF_DEMAND, A.PRF_DIR 
    


UNION 

SELECT DISTINCT                                                  -- CESUP REDE 
    127 AS cd_vrv,												-- QT PROCESSOS PROTOCOLADOS                    
    A.PRF_CESUP_REDE AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.PRF_DEMAND) AS vl_vrv,
    177 AS cd_in
FROM
    gac.PDCON_AUX2_CDC A
        LEFT JOIN (SELECT PRF_CESUP_REDE, SUM(PESO_IND) AS ATRASADOS FROM gac.PDCON_AUX2 WHERE DIF_DIAS < 0 GROUP BY PRF_CESUP_REDE) B 
        ON (B.PRF_CESUP_REDE = A.PRF_CESUP_REDE)
        
	WHERE A.PRF_CESUP_REDE IS NOT NULL
GROUP BY A.PRF_CESUP_REDE

UNION 

SELECT DISTINCT                                                 -- DIRETORIA
    127 AS cd_vrv,												-- QT PROCESSOS PROTOCOLADOS                    
    A.PRF_DIR AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.PRF_DEMAND) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX_CDC A
LEFT JOIN (SELECT PRF_DIR, SUM(PESO_IND) AS ATRASADOS FROM gac.PDCON_AUX  WHERE DIF_DIAS < 0 GROUP BY PRF_DIR) B
ON(B.PRF_DIR = A.PRF_DIR)

WHERE A.PRF_DIR IS NOT NULL

GROUP BY A.PRF_DIR

UNION 

SELECT DISTINCT                                                 -- VP
    127 AS cd_vrv,												-- QT PROCESSOS PROTOCOLADOS                    
    A.PRF_VP AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.PRF_DEMAND) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX_CDC A
LEFT JOIN (SELECT PRF_VP, SUM(PESO_IND) AS ATRASADOS FROM gac.PDCON_AUX_CDC  WHERE DIF_DIAS < 0 GROUP BY PRF_VP) B
ON(B.PRF_VP = A.PRF_VP)

WHERE A.PRF_VP = 8166

GROUP BY A.PRF_VP
 
UNION 

SELECT                                                              -- PREFIXO DEMANDANTE
    128 AS cd_vrv, 													-- QT PROCESSOS DEVOLVIDOS                                              
    A.PRF_DEMAND AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_CDC A

WHERE ((CD_RES_PROC = 2 AND CD_SUB_PROJ IN(60, 64, 115, 169, 197, 198, 199, 175, 155, 200, 208, 210, 211, 213, 214, 212, 225, 156, 233, 234, 235))
OR (CD_RES_PROC = 5 AND CD_SUB_PROJ IN(68, 69, 70, 71, 74, 62, 63, 64, 65, 66, 194))
OR (CD_RES_PROC = 1196 AND CD_SUB_PROJ IN(218))
OR (CD_RES_PROC = 1357 AND CD_SUB_PROJ IN(215))
OR (CD_RES_PROC = 1448 AND CD_SUB_PROJ IN(224))
OR (CD_RES_PROC = 1707 AND CD_SUB_PROJ IN(238))
OR (CD_SUB_PROJ IN(92, 118, 116, 117, 222, 232, 219) AND CD_RES_PROC = 2)
OR (CD_SUB_PROJ IN(72, 73, 60, 61, 115, 169, 175, 155, 200, 208, 210, 211, 213, 214, 212, 225, 156, 233, 234, 235) AND CD_RES_PROC = 5)
OR (CD_SUB_PROJ IN(68, 69, 70, 71, 74) AND CD_RES_PROC = 6)
OR (CD_SUB_PROJ IN(62, 63, 64, 65, 66) AND CD_RES_PROC = 8)
OR (CD_SUB_PROJ IN(218) AND CD_RES_PROC = 1199) 
OR (CD_SUB_PROJ IN(215) AND CD_RES_PROC = 1360)
OR (CD_SUB_PROJ IN(224) AND CD_RES_PROC = 1451)
OR (CD_SUB_PROJ IN(220) AND CD_RES_PROC = 1537)
OR (CD_SUB_PROJ IN(238) AND CD_RES_PROC = 1710)
OR (CD_SUB_PROJ IN(221) AND CD_RES_PROC = 1894))
AND (A.PRF_DEMAND <> A.PRF_DIR
AND A.PRF_DEMAND <> A.PRF_CESUP_REDE)
AND A.PRF_DEMAND IS NOT NULL

GROUP BY A.PRF_DEMAND

UNION

SELECT                                                              -- DIRETORIA 
    128 AS cd_vrv, 													-- QT PROCESSOS DEVOLVIDOS                                              
    A.PRF_DIR AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_CDC A

WHERE ((CD_RES_PROC = 2 AND CD_SUB_PROJ IN(60, 64, 115, 169, 197, 198, 199, 175, 155, 200, 208, 210, 211, 213, 214, 212, 225, 156, 233, 234, 235))
OR (CD_RES_PROC = 5 AND CD_SUB_PROJ IN(68, 69, 70, 71, 74, 62, 63, 64, 65, 66, 194))
OR (CD_RES_PROC = 1196 AND CD_SUB_PROJ IN(218))
OR (CD_RES_PROC = 1357 AND CD_SUB_PROJ IN(215))
OR (CD_RES_PROC = 1448 AND CD_SUB_PROJ IN(224))
OR (CD_RES_PROC = 1707 AND CD_SUB_PROJ IN(238))
OR (CD_SUB_PROJ IN(92, 118, 116, 117, 222, 232, 219) AND CD_RES_PROC = 2)
OR (CD_SUB_PROJ IN(72, 73, 60, 61, 115, 169, 175, 155, 200, 208, 210, 211, 213, 214, 212, 225, 156, 233, 234, 235) AND CD_RES_PROC = 5)
OR (CD_SUB_PROJ IN(68, 69, 70, 71, 74) AND CD_RES_PROC = 6)
OR (CD_SUB_PROJ IN(62, 63, 64, 65, 66) AND CD_RES_PROC = 8)
OR (CD_SUB_PROJ IN(218) AND CD_RES_PROC = 1199) 
OR (CD_SUB_PROJ IN(215) AND CD_RES_PROC = 1360)
OR (CD_SUB_PROJ IN(224) AND CD_RES_PROC = 1451)
OR (CD_SUB_PROJ IN(220) AND CD_RES_PROC = 1537)
OR (CD_SUB_PROJ IN(238) AND CD_RES_PROC = 1710)
OR (CD_SUB_PROJ IN(221) AND CD_RES_PROC = 1894))
AND A.PRF_DIR IS NOT NULL 

GROUP BY A.PRF_DIR

UNION 

SELECT                                                              -- VP 
    128 AS cd_vrv, 													-- QT PROCESSOS DEVOLVIDOS                                              
    A.PRF_VP AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_CDC A

WHERE ((CD_RES_PROC = 2 AND CD_SUB_PROJ IN(60, 64, 115, 169, 197, 198, 199, 175, 155, 200, 208, 210, 211, 213, 214, 212, 225, 156, 233, 234, 235))
OR (CD_RES_PROC = 5 AND CD_SUB_PROJ IN(68, 69, 70, 71, 74, 62, 63, 64, 65, 66, 194))
OR (CD_RES_PROC = 1196 AND CD_SUB_PROJ IN(218))
OR (CD_RES_PROC = 1357 AND CD_SUB_PROJ IN(215))
OR (CD_RES_PROC = 1448 AND CD_SUB_PROJ IN(224))
OR (CD_RES_PROC = 1707 AND CD_SUB_PROJ IN(238))
OR (CD_SUB_PROJ IN(92, 118, 116, 117, 222, 232, 219) AND CD_RES_PROC = 2)
OR (CD_SUB_PROJ IN(72, 73, 60, 61, 115, 169, 175, 155, 200, 208, 210, 211, 213, 214, 212, 225, 156, 233, 234, 235) AND CD_RES_PROC = 5)
OR (CD_SUB_PROJ IN(68, 69, 70, 71, 74) AND CD_RES_PROC = 6)
OR (CD_SUB_PROJ IN(62, 63, 64, 65, 66) AND CD_RES_PROC = 8)
OR (CD_SUB_PROJ IN(218) AND CD_RES_PROC = 1199) 
OR (CD_SUB_PROJ IN(215) AND CD_RES_PROC = 1360)
OR (CD_SUB_PROJ IN(224) AND CD_RES_PROC = 1451)
OR (CD_SUB_PROJ IN(220) AND CD_RES_PROC = 1537)
OR (CD_SUB_PROJ IN(238) AND CD_RES_PROC = 1710)
OR (CD_SUB_PROJ IN(221) AND CD_RES_PROC = 1894))
AND A.PRF_VP = 8166


GROUP BY A.PRF_VP

UNION

SELECT                                                              -- CESUP REDE
    128 AS cd_vrv, 													-- QT PROCESSOS DEVOLVIDOS                                              
    A.PRF_CESUP_REDE AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX2_CDC A

WHERE((CD_RES_PROC = 2 AND CD_SUB_PROJ IN(60, 64, 115, 169, 197, 198, 199, 175, 155, 200, 208, 210, 211, 213, 214, 212, 225, 156, 233, 234, 235))
OR (CD_RES_PROC = 5 AND CD_SUB_PROJ IN(68, 69, 70, 71, 74, 62, 63, 64, 65, 66, 194))
OR (CD_RES_PROC = 1196 AND CD_SUB_PROJ IN(218))
OR (CD_RES_PROC = 1357 AND CD_SUB_PROJ IN(215))
OR (CD_RES_PROC = 1448 AND CD_SUB_PROJ IN(224))
OR (CD_RES_PROC = 1707 AND CD_SUB_PROJ IN(238))
OR (CD_SUB_PROJ IN(92, 118, 116, 117, 222, 232, 219) AND CD_RES_PROC = 2)
OR (CD_SUB_PROJ IN(72, 73, 60, 61, 115, 169, 175, 155, 200, 208, 210, 211, 213, 214, 212, 225, 156, 233, 234, 235) AND CD_RES_PROC = 5)
OR (CD_SUB_PROJ IN(68, 69, 70, 71, 74) AND CD_RES_PROC = 6)
OR (CD_SUB_PROJ IN(62, 63, 64, 65, 66) AND CD_RES_PROC = 8)
OR (CD_SUB_PROJ IN(218) AND CD_RES_PROC = 1199) 
OR (CD_SUB_PROJ IN(215) AND CD_RES_PROC = 1360)
OR (CD_SUB_PROJ IN(224) AND CD_RES_PROC = 1451)
OR (CD_SUB_PROJ IN(220) AND CD_RES_PROC = 1537)
OR (CD_SUB_PROJ IN(238) AND CD_RES_PROC = 1710)
OR (CD_SUB_PROJ IN(221) AND CD_RES_PROC = 1894))
AND A.PRF_CESUP_REDE IS NOT NULL

GROUP BY A.PRF_CESUP_REDE


UNION

SELECT                                                              -- PREFIXO DEMANDANTE
    124 AS cd_vrv, 													-- QT PROCESSOS EM ATRASO RISCO 1                                    
    A.PRF_DEMAND AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX_SDC A
WHERE PESO_IND = 1
AND DIF_DIAS < 0
AND (A.PRF_DEMAND <> A.PRF_DIR AND A.PRF_DEMAND <> A.PRF_CESUP_REDE)
AND A.PRF_DEMAND IS NOT NULL

GROUP BY A.PRF_DEMAND

UNION

SELECT                                                              -- DIRETORIA
    124 AS cd_vrv, 													-- QT PROCESSOS EM ATRASO RISCO 1                                            
    A.PRF_DIR AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX_SDC A

WHERE PESO_IND = 1
AND DIF_DIAS < 0
AND A.PRF_DIR IS NOT NULL

GROUP BY A.PRF_DIR

UNION 

SELECT                                                              -- VP
    124 AS cd_vrv, 													-- QT PROCESSOS EM ATRASO RISCO 1                                            
    A.PRF_VP AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX_SDC A

WHERE PESO_IND = 1
AND DIF_DIAS < 0
AND A.PRF_VP = 8166


GROUP BY A.PRF_VP

UNION

SELECT                                                              -- CESUP
    124 AS cd_vrv, 													-- QT PROCESSOS EM ATRASO RISCO 1                                               
    A.PRF_CESUP_REDE AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX2_SDC A

WHERE PESO_IND = 1
AND DIF_DIAS < 0
AND  A.PRF_CESUP_REDE IS NOT NULL

GROUP BY A.PRF_CESUP_REDE

UNION 

SELECT                                                              -- DEMANDANTE
    125 AS cd_vrv, 													-- QT PROCESSOS EM ATRASO RISCO 2                                    
    A.PRF_DEMAND AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX_SDC A
WHERE PESO_IND = 1.5
AND DIF_DIAS < 0
AND (A.PRF_DEMAND <> A.PRF_DIR AND A.PRF_DEMAND <> A.PRF_CESUP_REDE)
AND A.PRF_DEMAND IS NOT NULL

GROUP BY A.PRF_DEMAND

UNION

SELECT                                                              -- DIRETORIA
    125 AS cd_vrv, 													-- QT PROCESSOS EM ATRASO RISCO 2                                            
    A.PRF_DIR AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX_SDC A

WHERE PESO_IND = 1.5
AND DIF_DIAS < 0
AND A.PRF_DIR IS NOT NULL

GROUP BY A.PRF_DIR

UNION 

SELECT                                                              -- VP
    125 AS cd_vrv, 													-- QT PROCESSOS EM ATRASO RISCO 2                                            
    A.PRF_VP AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX_SDC A

WHERE PESO_IND = 1.5
AND DIF_DIAS < 0
AND PRF_VP = 8166

GROUP BY A.PRF_VP

UNION 

SELECT                                                              -- CESUP
    125 AS cd_vrv, 													-- QT PROCESSOS EM ATRASO RISCO 2                                               
    A.PRF_CESUP_REDE AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX2_SDC A

WHERE PESO_IND = 1.5
AND DIF_DIAS < 0
AND A.PRF_CESUP_REDE IS NOT NULL

GROUP BY A.PRF_CESUP_REDE

UNION

SELECT                                                              -- DEMANDANTE
    126 AS cd_vrv, 													-- QT PROCESSOS EM ATRASO RISCO 3                                    
    A.PRF_DEMAND AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX_SDC A
WHERE PESO_IND = 2
AND DIF_DIAS < 0
AND (A.PRF_DEMAND <> A.PRF_DIR AND A.PRF_DEMAND <> A.PRF_CESUP_REDE)
AND A.PRF_DEMAND IS NOT NULL

GROUP BY A.PRF_DEMAND

UNION

SELECT                                                              -- DIRETORIA
    126 AS cd_vrv, 													-- QT PROCESSOS EM ATRASO RISCO 3                                            
    A.PRF_DIR AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX_SDC A

WHERE PESO_IND = 2
AND DIF_DIAS < 0
AND A.PRF_DIR IS NOT NULL

GROUP BY A.PRF_DIR

UNION 

SELECT                                                              -- VP
    126 AS cd_vrv, 													-- QT PROCESSOS EM ATRASO RISCO 3                                            
    A.PRF_VP AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX_SDC A

WHERE PESO_IND = 2
AND DIF_DIAS < 0
AND A.PRF_VP = 8166

GROUP BY A.PRF_VP

UNION 

SELECT                                                              -- CESUP
    126 AS cd_vrv, 													-- QT PROCESSOS EM ATRASO RISCO 3                                               
    A.PRF_CESUP_REDE AS cd_prf_depe,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    COUNT(A.NR_EVT) AS vl_vrv,
    177 AS cd_in
    
FROM gac.PDCON_AUX2_SDC A

WHERE PESO_IND = 2
AND DIF_DIAS < 0
AND A.PRF_CESUP_REDE IS NOT NULL

GROUP BY A.PRF_CESUP_REDE;

/******************************* GAC3  *****************************************/

DROP TABLE IF EXISTS gac.PADCON_GAC3;

CREATE TABLE gac.PADCON_GAC3
SELECT                                                                -- NÃO PERFORMADOS DEMANDANTE PESO 1
	24 AS cd_evt,
    177 AS cd_in,
    2 AS qlc_evt,
    A.PRF_DEMAND AS cd_prf_depe,
    QUOTE(CONCAT(A.AA_EVT, ' ', A.NR_EVT, ' ', A.PRF_DIR, ' ',@MES_REF)) AS nr_doc,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    DATEDIFF(CURDATE(), 19600101) AS dt_prct
    
FROM gac.PDCON_AUX_SDC A
WHERE PESO_IND = 1
AND DIF_DIAS < 0
AND (A.PRF_DEMAND <> A.PRF_DIR AND A.PRF_DEMAND <> A.PRF_CESUP_REDE)
AND  A.PRF_DEMAND IS NOT NULL

UNION

SELECT                                                                -- NÃO PERFORMADOS DIRETORIA PESO 1                                                          
    24 AS cd_evt,
    177 AS cd_in,
    2 AS qlc_evt,
    A.PRF_DIR AS cd_prf_depe,
    QUOTE(CONCAT(A.AA_EVT, ' ', A.NR_EVT, ' ', A.PRF_DIR, ' ',@MES_REF)) AS nr_doc,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    DATEDIFF(CURDATE(), 19600101) AS dt_prc
    
FROM gac.PDCON_AUX_SDC A

WHERE PESO_IND = 1
AND DIF_DIAS < 0
AND  A.PRF_DIR IS NOT NULL

UNION 

SELECT                                                                -- NÃO PERFORMADOS VP PESO 1                                                          
    24 AS cd_evt,
    177 AS cd_in,
    2 AS qlc_evt,
    A.PRF_VP AS cd_prf_depe,
    QUOTE(CONCAT(A.AA_EVT, ' ', A.NR_EVT, ' ', A.PRF_DIR, ' ',@MES_REF)) AS nr_doc,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    DATEDIFF(CURDATE(), 19600101) AS dt_prc
    
FROM gac.PDCON_AUX_SDC A

WHERE PESO_IND = 1
AND DIF_DIAS < 0
AND A.PRF_VP = 8166

UNION

SELECT                                                                     -- NÃO PERFORMADOS CESUP PESO 1
	24 AS cd_evt,
    177 AS cd_in,
    2 AS qlc_evt,
    A.PRF_CESUP_REDE AS cd_prf_depe,
    QUOTE(CONCAT(A.AA_EVT, ' ', A.NR_EVT, ' ', A.PRF_DIR, ' ',@MES_REF)) AS nr_doc,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    DATEDIFF(CURDATE(), 19600101) AS dt_prc
    
FROM gac.PDCON_AUX2_SDC A

WHERE PESO_IND = 1
AND DIF_DIAS < 0
AND A.PRF_CESUP_REDE IS NOT NULL

UNION

SELECT                                                                               -- NÃO PERFORMADOS TIPO 2 DEMANDANTE
	25 AS cd_evt,
    177 AS cd_in,
    2 AS qlc_evt,
    A.PRF_DEMAND AS cd_prf_depe,
    QUOTE(CONCAT(A.AA_EVT, ' ', A.NR_EVT, ' ',A.PRF_DIR, ' ', @MES_REF)) AS nr_doc,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    DATEDIFF(CURDATE(), 19600101) AS dt_prct
    
FROM gac.PDCON_AUX_SDC A
WHERE PESO_IND = 1.5
AND DIF_DIAS < 0
AND (A.PRF_DEMAND <> A.PRF_DIR AND  A.PRF_DEMAND <> A.PRF_CESUP_REDE)
AND A.PRF_DEMAND IS NOT NULL

UNION

SELECT                                                                   -- NÃO PERFORMADO TIPO 2 DIRETORIA
    25 AS cd_evt,
    177 AS cd_in,
    2 AS qlc_evt,
    A.PRF_DIR AS cd_prf_depe,
    QUOTE(CONCAT(A.AA_EVT, ' ', A.NR_EVT, ' ',A.PRF_DIR, ' ', @MES_REF)) AS nr_doc,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    DATEDIFF(CURDATE(), 19600101) AS dt_prc
    
FROM gac.PDCON_AUX_SDC A

WHERE PESO_IND = 1.5
AND DIF_DIAS < 0
AND A.PRF_DIR IS NOT NULL

UNION 

SELECT                                                                   -- NÃO PERFORMADO TIPO 2 VP
    25 AS cd_evt,
    177 AS cd_in,
    2 AS qlc_evt,
    A.PRF_VP AS cd_prf_depe,
    QUOTE(CONCAT(A.AA_EVT, ' ', A.NR_EVT, ' ',A.PRF_DIR, ' ', @MES_REF)) AS nr_doc,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    DATEDIFF(CURDATE(), 19600101) AS dt_prc
    
FROM gac.PDCON_AUX_SDC A

WHERE PESO_IND = 1.5
AND DIF_DIAS < 0
AND A.PRF_VP = 8166

UNION

SELECT                                                                  -- NÃO PERFORMADO TIPO 2 CESUP
	25 AS cd_evt,
    177 AS cd_in,
    2 AS qlc_evt,
    A.PRF_CESUP_REDE AS cd_prf_depe,
    QUOTE(CONCAT(A.AA_EVT, ' ', A.NR_EVT, ' ', A.PRF_DIR, ' ',@MES_REF)) AS nr_doc,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    DATEDIFF(CURDATE(), 19600101) AS dt_prc
    
FROM gac.PDCON_AUX2_SDC A

WHERE PESO_IND = 1.5
AND DIF_DIAS < 0
AND A.PRF_CESUP_REDE IS NOT NULL

UNION

SELECT                                                                     -- NÃO PERFORMADO TIPO 3 DEMANDANTE
	26 AS cd_evt,
    177 AS cd_in,
    2 AS qlc_evt,
    A.PRF_DEMAND AS cd_prf_depe,
    QUOTE(CONCAT(A.AA_EVT, ' ', A.NR_EVT, ' ',A.PRF_DIR, ' ', @MES_REF)) AS nr_doc,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    DATEDIFF(CURDATE(), 19600101) AS dt_prct
    
FROM gac.PDCON_AUX_SDC A
WHERE PESO_IND = 2
AND DIF_DIAS < 0
AND (A.PRF_DEMAND <> A.PRF_DIR AND A.PRF_DEMAND <> A.PRF_CESUP_REDE)
AND A.PRF_DEMAND IS NOT NULL

UNION

SELECT                                                                  -- NÃO PERFORMADO TIPO 3 DIRETORIA
    26 AS cd_evt,
    177 AS cd_in,
    2 AS qlc_evt,
    A.PRF_DIR AS cd_prf_depe,
    QUOTE(CONCAT(A.AA_EVT, ' ', A.NR_EVT, ' ',A.PRF_DIR, ' ', @MES_REF)) AS nr_doc,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    DATEDIFF(CURDATE(), 19600101) AS dt_prc
    
FROM gac.PDCON_AUX_SDC A

WHERE PESO_IND = 2
AND DIF_DIAS < 0
AND A.PRF_DIR IS NOT NULL

UNION 

SELECT                                                                  -- NÃO PERFORMADO TIPO 3 VP
    26 AS cd_evt,
    177 AS cd_in,
    2 AS qlc_evt,
    A.PRF_VP AS cd_prf_depe,
    QUOTE(CONCAT(A.AA_EVT, ' ', A.NR_EVT, ' ',A.PRF_DIR, ' ', @MES_REF)) AS nr_doc,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    DATEDIFF(CURDATE(), 19600101) AS dt_prc
    
FROM gac.PDCON_AUX_SDC A

WHERE PESO_IND = 2
AND DIF_DIAS < 0
AND A.PRF_VP = 8166

UNION

SELECT                                                              -- NÃO PERFORMADO TIPO 3 CESUP
	26 AS cd_evt,
    177 AS cd_in,
    2 AS qlc_evt,
    A.PRF_CESUP_REDE AS cd_prf_depe,
    QUOTE(CONCAT(A.AA_EVT, ' ', A.NR_EVT, ' ', A.PRF_DIR, ' ', @MES_REF)) AS nr_doc,
    @ANO_REF AS ano_ref,
    @MES_REF AS mes_ref,
    DATEDIFF(CURDATE(), 19600101) AS dt_prc
    
FROM gac.PDCON_AUX2_SDC A

WHERE PESO_IND = 2
AND DIF_DIAS < 0
AND A.PRF_CESUP_REDE IS NOT NULL;


DROP TABLE fluxoAux.GAC_PDCON_BASE_SEM_FILTRO;

CREATE TABLE fluxoAux.GAC_PDCON_BASE_SEM_FILTRO
SELECT DISTINCT 
	A.CD_SUB_PROJ,
	A.AA_EVT, 
	A.NR_EVT, 
	A.TX_EVT,
	A.CD_FASE_EVT, 
	A.CD_PRF_EXEC, 
	I.VL_ATB_EVT_INT AS PRF_DEMAND, 
    O.NM_UOR_RED AS DEMAND,
	L.CD_PRF AS PRF_CESUP_REDE, 
	L.NM_UOR_RED AS CESUP_REDE,
	G.CD_PRF AS PRF_DIR,
	G.NM_UOR_RED AS DIRETORIA,
    R.CD_PRF AS PRF_VP, 
    R.NM_UOR_RED AS VP,
	DATE(A.TS_CRIC_EVT) AS DT_CRIC_EVT,
	A.CD_USU_CRIC_EVT, 
	H.prefixo_lotacao AS PRF_USU_CRIC,
	A.DT_INC_EVT, 
	A.DT_FIM_EVT, 
    P.VL_ATB_EVT_INT AS CD_RES_PROC,
    Q.TX_LS_OPC_ATB AS RES_PROC,
    M.VL_ATB_EVT_INT,
	N.TX_LS_OPC_ATB AS EQD_LGAL,
	T.TX_LS_OPC_ATB AS SINISTRO,
	B.VL_ATB_EVT_DT AS DT_LIM , 
	C.VL_ATB_EVT_INT AS PZ_ETGA, 
	D.VL_ATB_EVT_INT AS PZ_AVL, 
	CASE 
		-- ALTERAÇÃO SOLICITADA POR DICAD DEMANDA 2019/144833 - INÍCIO
        -- WHEN A.CD_SUB_PROJ IN(117, 216, 217) THEN 26
        WHEN A.CD_SUB_PROJ IN(216) THEN 26  										
        WHEN A.CD_SUB_PROJ IN(117, 217) THEN 15
        -- ALTERAÇÃO SOLICITADA POR DICAD DEMANDA 2019/144833 - FIM
		WHEN A.CD_SUB_PROJ IN(68, 69, 73, 74, 208, 215, 218, 219, 220, 222) THEN 30
		WHEN A.CD_SUB_PROJ IN (212, 214, 225) THEN 33
		WHEN A.CD_SUB_PROJ IN (213) THEN 43
		WHEN A.CD_SUB_PROJ IN(210, 211, 238, 363) THEN 132
	END AS PZ_IND,      -- PRAZO DE LICITAÇÃO POR SUBPROJETO EM DIAS
	CASE 
		WHEN A.CD_SUB_PROJ IN(68, 69, 73, 74, 92, 115, 117, 169, 208, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223) THEN 1
		WHEN A.CD_SUB_PROJ IN (210, 211, 238, 363) THEN 1.5
		WHEN A.CD_SUB_PROJ IN (212, 225) THEN 2
	END AS PESO_IND,     -- PESO DO INDICADOR POR SUBPROJETO EM DIAS
    CASE  
			WHEN A.NR_EVT IN (SELECT DISTINCT NR_EVT_PAI FROM fluxoTrabalho.evt WHERE AA_EVT_PAI > 0 AND NR_EVT_PAI > 0) THEN 1
			WHEN A.AA_EVT_PAI > 0 AND A.NR_EVT_PAI > 0 THEN 2
			ELSE 0
	END AS EVT_PRINCIPAL

	FROM fluxoTrabalho.evt A

	LEFT JOIN fluxoTrabalho.ctu_atb_evt B ON(B.CD_SUB_PROJ = A.CD_SUB_PROJ AND B.AA_EVT = A.AA_EVT AND B.NR_EVT = A.NR_EVT AND B.CD_ATB IN(407, 441, 444, 447, 456, 457, 460, 463, 466, 469, 472, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530))  -- DATA LIMITE
	LEFT JOIN fluxoTrabalho.ctu_atb_evt C ON(C.CD_SUB_PROJ = A.CD_SUB_PROJ AND C.AA_EVT = A.AA_EVT AND C.NR_EVT = A.NR_EVT AND C.CD_ATB IN(406, 442, 445, 448, 452, 454, 458, 461, 464, 467, 470, 473))  -- PRAZO DE ENTREGA
	LEFT JOIN fluxoTrabalho.ctu_atb_evt D ON(D.CD_SUB_PROJ = A.CD_SUB_PROJ AND D.AA_EVT = A.AA_EVT AND D.NR_EVT = A.NR_EVT AND D.CD_ATB IN(410, 443, 446, 449, 453, 455, 459, 462, 465, 468, 471, 474))    -- PRAZO AVALIACAO
	LEFT JOIN fluxoTrabalho.ctu_atb_evt I ON(I.CD_SUB_PROJ = A.CD_SUB_PROJ AND I.AA_EVT = A.AA_EVT AND I.NR_EVT = A.NR_EVT AND  I.CD_ATB IN(504, 505, 798, 800, 1043, 1126, 1166, 1207)) -- PREFIXO DEMANDANTE
	LEFT JOIN fluxoTrabalho.ctu_atb_evt M ON(M.CD_SUB_PROJ = A.CD_SUB_PROJ AND M.AA_EVT = A.AA_EVT AND M.NR_EVT = A.NR_EVT AND  M.CD_ATB IN(385))  -- ENQUADRAMENTO LEGAL
	LEFT JOIN fluxoTrabalho.ls_opc_atb N ON(N.NR_SEQL_LS_OPC = M.VL_ATB_EVT_INT AND M.CD_ATB = N.CD_ATB)
    LEFT JOIN fluxoTrabalho.ctu_atb_evt P ON(P.CD_SUB_PROJ = A.CD_SUB_PROJ AND P.AA_EVT = A.AA_EVT AND P.NR_EVT = A.NR_EVT AND P.CD_ATB IN(175, 427, 496)) -- RESULTADO FINAL DO PROCESSO
    LEFT JOIN fluxoTrabalho.ls_opc_atb Q ON(Q.NR_SEQL_LS_OPC = P.VL_ATB_EVT_INT AND Q.CD_ATB = P.CD_ATB  AND P.CD_SUB_PROJ = Q.CD_SUB_PROJ ) -- RESPONS PROCESSO
	LEFT JOIN mstNovo.depe E ON(E.CD_PRF = I.VL_ATB_EVT_INT AND E.CD_SBDD = 0)
	LEFT JOIN mstNovo.depe_jrdc K ON(K.CD_UOR_JRDD = E.CD_UOR AND K.CD_JRDC = 2819)
	LEFT JOIN mstNovo.depe L ON(L.CD_UOR = K.CD_UOR_JRDT)
	LEFT JOIN mstNovo.depe_jrdc F ON(F.CD_UOR_JRDD = E.CD_UOR AND F.CD_JRDC = 1200)
	LEFT JOIN mstNovo.depe G ON(G.CD_UOR = F.CD_UOR_JRDT)
	LEFT JOIN arh_dipes.arhfot01 H ON(H.matricula = A.CD_USU_CRIC_EVT)
    LEFT JOIN mstNovo.depe O ON(O.CD_PRF = I.VL_ATB_EVT_INT AND O.CD_SBDD = 0)  
    LEFT JOIN mstNovo.depe P ON(P.CD_PRF = I.VL_ATB_EVT_INT AND P.CD_SBDD = 0) 
    LEFT JOIN mstNovo.depe_jrdc Q ON(Q.CD_UOR_JRDD = P.CD_UOR AND Q.CD_JRDC = 1220)
    LEFT JOIN mstNovo.depe R ON(R.CD_UOR = Q.CD_UOR_JRDT)
    LEFT JOIN fluxoTrabalho.ctu_atb_evt S ON(S.CD_SUB_PROJ = A.CD_SUB_PROJ AND S.AA_EVT = A.AA_EVT AND S.NR_EVT = A.NR_EVT AND S.CD_ATB IN(653, 654, 655, 656, 657, 1154, 1169, 1209))  -- SINISTRO
    LEFT JOIN fluxoTrabalho.ls_opc_atb T ON(T.NR_SEQL_LS_OPC = S.VL_ATB_EVT_INT AND T.CD_ATB = S.CD_ATB)
   
	WHERE 
	A.TS_CRIC_EVT  >= 20180101
	AND A.CD_SUB_PROJ IN (117, 217, 68, 69, 74, 215, 216, 219, 220, 212, 214, 225, 213, 210, 211, 238, 363)
    AND I.VL_ATB_EVT_INT > 0
	
	GROUP BY CD_SUB_PROJ, AA_EVT, NR_EVT, I.VL_ATB_EVT_INT
    
UNION 

	SELECT DISTINCT 
		A.CD_SUB_PROJ,
		A.AA_EVT, 
		A.NR_EVT, 
		A.TX_EVT,
		A.CD_FASE_EVT, 
		A.CD_PRF_EXEC, 
		I.VL_ATB_EVT_INT AS PRF_DEMAND, 
		O.NM_UOR_RED AS DEMAND,
		L.CD_PRF AS PRF_CESUP_REDE, 
		L.NM_UOR_RED AS CESUP_REDE,
		9903 AS PRF_DIR,
		'DITEC-TECNOLOGIA' AS DIRETORIA,
		8033 AS PRF_VP, 
		'VITEC' AS VP,
		DATE(A.TS_CRIC_EVT) AS DT_CRIC_EVT,
		A.CD_USU_CRIC_EVT, 
		H.prefixo_lotacao AS PRF_USU_CRIC,
		A.DT_INC_EVT, 
		A.DT_FIM_EVT, 
		P.VL_ATB_EVT_INT AS CD_RES_PROC,
		Q.TX_LS_OPC_ATB AS RES_PROC,
		M.VL_ATB_EVT_INT,
		N.TX_LS_OPC_ATB AS EQD_LGAL,
         T.TX_LS_OPC_ATB AS SINISTRO,
		B.VL_ATB_EVT_DT AS DT_LIM , 
		C.VL_ATB_EVT_INT AS PZ_ETGA, 
		D.VL_ATB_EVT_INT AS PZ_AVL, 
		CASE 
			-- ALTERAÇÃO SOLICITADA POR DICAD DEMANDA 2019/144833 - INÍCIO
			-- WHEN A.CD_SUB_PROJ IN(117, 216, 217) THEN 26
			WHEN A.CD_SUB_PROJ IN(216) THEN 26  										
			WHEN A.CD_SUB_PROJ IN(117, 217) THEN 15
			-- ALTERAÇÃO SOLICITADA POR DICAD DEMANDA 2019/144833 - FIM
			WHEN A.CD_SUB_PROJ IN(68, 69, 73, 74, 208, 215, 218, 219, 220, 222) THEN 30
			WHEN A.CD_SUB_PROJ IN (212, 214, 225) THEN 33
			WHEN A.CD_SUB_PROJ IN (213) THEN 43
			WHEN A.CD_SUB_PROJ IN(210, 211, 238, 363) THEN 132
		END AS PZ_IND,      -- PRAZO DE LICITAÇÃO POR SUBPROJETO EM DIAS
		CASE 
			WHEN A.CD_SUB_PROJ IN(68, 69, 73, 74, 92, 115, 117, 169, 208, 213, 214, 215, 216, 217, 218, 219, 220,221, 222, 223, 224) THEN 1
			WHEN A.CD_SUB_PROJ IN (210, 211, 238, 363) THEN 1.5
			WHEN A.CD_SUB_PROJ IN (212, 225) THEN 2
		END AS PESO_IND,     -- PESO DO INDICADOR POR SUBPROJETO EM DIAS
        CASE  
			WHEN A.NR_EVT IN (SELECT DISTINCT NR_EVT_PAI FROM fluxoTrabalho.evt WHERE AA_EVT_PAI > 0 AND NR_EVT_PAI > 0) THEN 1
			WHEN A.AA_EVT_PAI > 0 AND A.NR_EVT_PAI > 0 THEN 2
			ELSE 0
		END AS EVT_PRINCIPAL


		FROM fluxoTrabalho.evt A

		LEFT JOIN fluxoTrabalho.ctu_atb_evt B ON(B.CD_SUB_PROJ = A.CD_SUB_PROJ AND B.AA_EVT = A.AA_EVT AND B.NR_EVT = A.NR_EVT AND B.CD_ATB IN(407, 441, 444, 447, 456, 457, 460, 463, 466, 469, 472, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530))  -- DATA LIMITE
		LEFT JOIN fluxoTrabalho.ctu_atb_evt C ON(C.CD_SUB_PROJ = A.CD_SUB_PROJ AND C.AA_EVT = A.AA_EVT AND C.NR_EVT = A.NR_EVT AND C.CD_ATB IN(406, 442, 445, 448, 452, 454, 458, 461, 464, 467, 470, 473))  -- PRAZO DE ENTREGA
		LEFT JOIN fluxoTrabalho.ctu_atb_evt D ON(D.CD_SUB_PROJ = A.CD_SUB_PROJ AND D.AA_EVT = A.AA_EVT AND D.NR_EVT = A.NR_EVT AND D.CD_ATB IN(410, 443, 446, 449, 453, 455, 459, 462, 465, 468, 471, 474))    -- PRAZO AVALIACAO
		LEFT JOIN fluxoTrabalho.ctu_atb_evt I ON(I.CD_SUB_PROJ = A.CD_SUB_PROJ AND I.AA_EVT = A.AA_EVT AND I.NR_EVT = A.NR_EVT AND  I.CD_ATB IN(504,505, 798, 800, 1043, 1126, 1166, 1207)) -- PREFIXO DEMANDANTE
		LEFT JOIN fluxoTrabalho.ctu_atb_evt M ON(M.CD_SUB_PROJ = A.CD_SUB_PROJ AND M.AA_EVT = A.AA_EVT AND M.NR_EVT = A.NR_EVT AND  M.CD_ATB IN(385))  -- ENQUADRAMENTO LEGAL
		LEFT JOIN fluxoTrabalho.ls_opc_atb N ON(N.NR_SEQL_LS_OPC = M.VL_ATB_EVT_INT AND M.CD_ATB = N.CD_ATB)
		LEFT JOIN fluxoTrabalho.ctu_atb_evt P ON(P.CD_SUB_PROJ = A.CD_SUB_PROJ AND P.AA_EVT = A.AA_EVT AND P.NR_EVT = A.NR_EVT AND P.CD_ATB IN(175, 427, 496)) -- RESULTADO FINAL DO PROCESSO
		LEFT JOIN fluxoTrabalho.ls_opc_atb Q ON(Q.NR_SEQL_LS_OPC = P.VL_ATB_EVT_INT AND Q.CD_ATB = P.CD_ATB  AND P.CD_SUB_PROJ = Q.CD_SUB_PROJ ) -- RESPONS PROCESSO
		LEFT JOIN mstNovo.depe E ON(E.CD_PRF = I.VL_ATB_EVT_INT AND E.CD_SBDD = 0)
		LEFT JOIN mstNovo.depe_jrdc K ON(K.CD_UOR_JRDD = E.CD_UOR AND K.CD_JRDC = 2819)
		LEFT JOIN mstNovo.depe L ON(L.CD_UOR = K.CD_UOR_JRDT)
		LEFT JOIN mstNovo.depe_jrdc F ON(F.CD_UOR_JRDD = E.CD_UOR AND F.CD_JRDC = 1200)
		LEFT JOIN mstNovo.depe G ON(G.CD_UOR = F.CD_UOR_JRDT)
		LEFT JOIN arh_dipes.arhfot01 H ON(H.matricula = A.CD_USU_CRIC_EVT)
		LEFT JOIN mstNovo.depe O ON(O.CD_PRF = I.VL_ATB_EVT_INT AND O.CD_SBDD = 0)  
		LEFT JOIN mstNovo.depe P ON(P.CD_PRF = I.VL_ATB_EVT_INT AND P.CD_SBDD = 0) 
		LEFT JOIN mstNovo.depe_jrdc Q ON(Q.CD_UOR_JRDD = P.CD_UOR AND Q.CD_JRDC = 1220)
		LEFT JOIN mstNovo.depe R ON(R.CD_UOR = Q.CD_UOR_JRDT)
        LEFT JOIN fluxoTrabalho.ctu_atb_evt S ON(S.CD_SUB_PROJ = A.CD_SUB_PROJ AND S.AA_EVT = A.AA_EVT AND S.NR_EVT = A.NR_EVT AND S.CD_ATB IN(653, 654, 655, 656, 657, 1154, 1169, 1209))  -- SINISTRO
        LEFT JOIN fluxoTrabalho.ls_opc_atb T ON(T.NR_SEQL_LS_OPC = S.VL_ATB_EVT_INT AND T.CD_ATB = S.CD_ATB)
	   
		WHERE 
		A.TS_CRIC_EVT > 20180101
		AND A.CD_SUB_PROJ IN (117, 217, 68, 69, 74, 215, 216, 219, 220, 212, 214, 225, 213, 210, 211, 238, 363)
		AND I.VL_ATB_EVT_INT = 8969
        AND I.VL_ATB_EVT_INT > 0

	GROUP BY CD_SUB_PROJ, AA_EVT, NR_EVT, I.VL_ATB_EVT_INT
;

SELECT
	'VALUES(',
	cd_bloc,
	',',
	cd_in,
	',',
	cd_prf_depe,
	',',
	ano_ref,
	',',
	mes_ref,
	',',
	dt_prct,
	',',
	pc_rstd,
	',',
	cd_rstd,
	',',
	tx_jst_rstd,
	')'
FROM 
	gac.PADCON_GAC1
	;


SELECT
	'VALUES(',
	cd_vrv,
	',',
	cd_prf_depe,
	',',
	ano_ref,
	',',
	mes_ref,
	',',
	vl_vrv,
	',',
	cd_in,
	')'
FROM 
	gac.PADCON_GAC2
;



SELECT
	'VALUES(',
	cd_evt,
	',',
	cd_in,
	',',
	qlc_evt,
	',',
	cd_prf_depe,
	',',
	nr_doc,
	',',
	ano_ref,
	',',
	mes_ref,
	',',
	dt_prct,
	')'
FROM 
	gac.PADCON_GAC3
;



-- https://bam.bb.com.br/spotfire/wp/OpenAnalysis?file=/%5BRestrita%5D/VISIN/Disec/Cesup/Todos/ATB/2019%20-%20GAC%20-%20PDCON%20-%20DISEC%20GERAL
-- verificar o motivo da discrepancia nos números.  

