DROP TABLE test.RUBRICAS02;

CREATE TABLE test.RUBRICAS02
SELECT 
	PRF,
	PRF_NOM,
	CONTA,
	CONTA_NOM,
	SALDO,
	DT_MOV,
	DT_BASE,
	QT_DIAS,
	RUBRICA,
	SIT,
	MM_REF  
FROM 
	test.RUBRICA01;

TRUNCATE TABLE test.RUBRICAS02;

LOAD DATA INFILE '/dados/arquivos/arqs/RUBRICAS/RUBRICAS_2020_01.csv'
			INTO TABLE test.RUBRICAS02
			FIELDS TERMINATED BY ';'
			LINES TERMINATED BY '\n'
            ;

-- SELECT * FROM test.RUBRICAS02;          

INSERT INTO gac.RUBRICAS_2020_01 SELECT * FROM test.RUBRICAS02;

SELECT * FROM gac.RUBRICAS_2020_01;