DROP TABLE test.LAUDO08;

CREATE TABLE test.LAUDO08
SELECT 
	NR_UNVL_TERR, 
	NR_UNVL, 
	VENC_A_VENC, 
	EXCLUIDO
FROM 
	test.LAUDO11;

DELETE FROM test.LAUDO08;

LOAD DATA INFILE '/dados/arquivos/arqs/LAUDOS/LAUDOS_2020_01.csv'
			INTO TABLE test.LAUDO08
			FIELDS TERMINATED BY ';'
			LINES TERMINATED BY '\n'
            -- ignore 1 lines
            ;

INSERT INTO gac.LAUDOS_2020_1 
SELECT 
A.NR_UNVL_TERR, 
A.NR_UNVL, 
A.VENC_A_VENC, 
A.EXCLUIDO, 
(MONTH(CURDATE())-1) AS MES_REF
FROM test.LAUDO08 A
;          


SELECT * FROM gac.LAUDOS_2020_1;

